services:
  mysql:
    image: mysql:8.0
    container_name: spd_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: spd_gerencia
      MYSQL_USER: spd_user
      MYSQL_PASSWORD: spd_pass
    ports:
      - "3306:3306"
    volumes:
      - spd_mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  spd_mysql_data:
