export const conveniosData = [
  {
    "Data Inicial": 44393,
    "Modalidade do Repasse": "Emenda",
    "Proposta/ Demanda": "031513/2021",
    "Termo de  Formalização": "Contrato de Repasse",
    "Número do Termo": 916433,
    "Data de Assinatura": 44468,
    "Ano": 2021,
    "Vigência": 46326,
    "Cláusula Suspensiva": null,
    "Esfera": "Federal",
    "Situação": "Assinado",
    "Parlamentar": "RELATOR GERAL / EMENDA 740\n3088 - EDUARDO BOLSONARO , 3777 - VITOR LIPPI",
    "Partido Político": "PL / PSDB",
    "Código da Emenda": 202181000740,
    "Função": "15 - Urbanismo",
    "Subfunção": "451 - Infra-Estrutura Urbana",
    "Código da Receita": null,
    "Repasse": 238856,
    "Contrapartida": 10556.89,
    "Ministério": "Cidades",
    "Programa": "Programa 2217 - Ação\nOrçamentária 1D73 – Apoio a Política Nacional de Desenvolvimento Urbano e Qualificação Viária",
    "Objeto": "Recapeamento da Rua Victório Zanchetta e Cezina de Almeida",
    "Conta Bancária": "006.006647054-0\n574185931-0",
    "Valor Liberado": 230338.43,
    "Data do depósito": 45849,
    "Modalidade": "Concorrência Pública",
    "Número/Ano": "005/2023",
    "Contrato nº": "032/2024",
    "Contratada": "Nogueira Construções e Serviços Ltda",
    "Vigência do Contrato": "12 Meses a partir da Assinatura do Contrato",
    "Assinatura do Contrato": 45412,
    "Término da Vigência": 45777,
    "Aditamento de vigência": null,
    "Prazo de Execução": "02 Meses a partir da OIS",
    "Ordem de Início de Serviço": null,
    "Término da Execução": null,
    "Aditamento de Execução": null,
    "Valor do Contrato": 230338.43,
    "Ficha Orçamentária RP": null,
    "Nota de Empenho RP": null,
    "RP Vigente": 226199.31,
    "Ficha Orçamentária CP": null,
    "Nota de Empenho CP": null,
    "CP Vigente": 2977.4,
    "Nota de Empenho Excl": null,
    "Ficha Orçamentária Excl": null,
    "CP Exclusiva/Recurso Próprio": 1161.72,
    "Aditamento de Valor": null,
    "CNO": null,
    "% Medição": 0,
    "Valor Pago": null,
    "% Pago": 0,
    "Saldo de RP": 230338.43,
    "Saldo na conta (rendimentos)": 3622.91,
    "Prestação de Contas": null,
    "Processo SPD": "3909/2021",
    "Processo Crédito Adicional": null,
    "Processo Licitatório": "8528/2023\n1678/2025",
    "Processo Medição": null,
    "Data da Última Medição/Movimentação": null,
    "Dias sem medição": null,
    "Dias sem movimentação": null,
    "Pendências": "Em elaboração do ETP e despacho para o DCLC - Processo Licitatório FEDERAL e ESTADUAL",
    "Órgão Responsável pela pendência": "SOURB / SPD",
    "Engenheiro Responsável": "Adilson",
    "Situação_1": null,
    "Área": "INFRAESTRUTURA"
  },
  {
    "Data Inicial": 43881,
    "Modalidade do Repasse": "Programa",
    "Proposta/ Demanda": "017413\n076464",
    "Termo de  Formalização": "Convênio",
    "Número do Termo": 128,
    "Data de Assinatura": 44545,
    "Ano": 2021,
    "Vigência": 46369,
    "Cláusula Suspensiva": null,
    "Esfera": "Estadual",
    "Situação": "Assinado",
    "Parlamentar": null,
    "Partido Político": null,
    "Código da Emenda": null,
    "Função": "13 - Cultura",
    "Subfunção": "392 - Difusão Cultural",
    "Código da Receita": null,
    "Repasse": 615073.96,
    "Contrapartida": 34675.87,
    "Ministério": "Turismo",
    "Programa": "MIT - Município de Interesse Turístico de Votorantim - 584 - Infraestrutura Turística",
    "Objeto": "Revitalização do Prédio da Biblioteca para instalação do Museu",
    "Conta Bancária": "31122-7",
    "Valor Liberado": 307536.98,
    "Data do depósito": 44923,
    "Modalidade": "Tomada de Preços (Lei 8.666)",
    "Número/Ano": "007/2022",
    "Contrato nº": "071/2022",
    "Contratada": "DCA Engenharia e Construções Eireli-EPP",
    "Vigência do Contrato": "12 Meses a partir da Assinatura do Contrato",
    "Assinatura do Contrato": 44748,
    "Término da Vigência": 45113,
    "Aditamento de vigência": 45414,
    "Prazo de Execução": "06 Meses a partir da OIS",
    "Ordem de Início de Serviço": 44900,
    "Término da Execução": 45080,
    "Aditamento de Execução": 45383,
    "Valor do Contrato": 675296.76,
    "Ficha Orçamentária RP": null,
    "Nota de Empenho RP": null,
    "RP Vigente": 456206.1,
    "Ficha Orçamentária CP": null,
    "Nota de Empenho CP": null,
    "CP Vigente": 0,
    "Nota de Empenho Excl": null,
    "Ficha Orçamentária Excl": null,
    "CP Exclusiva/Recurso Próprio": 219090.66,
    "Aditamento de Valor": 219090.66,
    "CNO": "90.013.14269/76",
    "% Medição": null,
    "Valor Pago": 306694.13,
    "% Pago": 0.454162004272018,
    "Saldo de RP": 842.849999999977,
    "Saldo na conta (rendimentos)": null,
    "Prestação de Contas": "Parcial",
    "Processo SPD": "5912/2021",
    "Processo Crédito Adicional": "9771/2022",
    "Processo Licitatório": "9776/2021\n357/2025",
    "Processo Medição": "7939/2022",
    "Data da Última Medição/Movimentação": 45125,
    "Dias sem medição": 742,
    "Dias sem movimentação": null,
    "Pendências": "1. Aguardando vistoria\n2. CE 05/2025 - Pintura - Aguardando homologação                                                   \n3. Aguardando parecer jurídico",
    "Órgão Responsável pela pendência": "1. DADETUR\n2. DCLC",
    "Engenheiro Responsável": "Fábio",
    "Situação_1": null,
    "Área": "CULTURA"
  },
  {
    "Data Inicial": 44672,
    "Modalidade do Repasse": "Emenda",
    "Proposta/ Demanda": "09032022-2-022112",
    "Termo de  Formalização": "Transferência Especial",
    "Número do Termo": "09032022-2-022112",
    "Data de Assinatura": 45014,
    "Ano": 2022,
    "Vigência": 46094,
    "Cláusula Suspensiva": null,
    "Esfera": "Federal",
    "Situação": "Assinado",
    "Parlamentar": "2356 - Arnaldo Jardim",
    "Partido Político": "Cidadania",
    "Código da Emenda": 202223560001,
    "Função": "28 - Encargos especiais",
    "Subfunção": "845 - Outras transferências",
    "Código da Receita": null,
    "Repasse": 300000,
    "Contrapartida": null,
    "Ministério": "Fazenda",
    "Programa": "Transferência Especial – Investimento",
    "Objeto": "Aquisição de equipamentos e material permanente na Clínica Veterinária Municipal",
    "Conta Bancária": "6672006-6\n575858238-3",
    "Valor Liberado": 300000,
    "Data do depósito": 45015,
    "Modalidade": null,
    "Número/Ano": null,
    "Contrato nº": null,
    "Contratada": null,
    "Vigência do Contrato": null,
    "Assinatura do Contrato": null,
    "Término da Vigência": null,
    "Aditamento de vigência": null,
    "Prazo de Execução": null,
    "Ordem de Início de Serviço": null,
    "Término da Execução": null,
    "Aditamento de Execução": null,
    "Valor do Contrato": null,
    "Ficha Orçamentária RP": null,
    "Nota de Empenho RP": null,
    "RP Vigente": null,
    "Ficha Orçamentária CP": null,
    "Nota de Empenho CP": null,
    "CP Vigente": null,
    "Nota de Empenho Excl": null,
    "Ficha Orçamentária Excl": null,
    "CP Exclusiva/Recurso Próprio": null,
    "Aditamento de Valor": null,
    "CNO": null,
    "% Medição": null,
    "Valor Pago": null,
    "% Pago": null,
    "Saldo de RP": 300000,
    "Saldo na conta (rendimentos)": 129919.2,
    "Prestação de Contas": null,
    "Processo SPD": "3520/2022",
    "Processo Crédito Adicional": null,
    "Processo Licitatório": "1174/2025",
    "Processo Medição": null,
    "Data da Última Medição/Movimentação": null,
    "Dias sem medição": null,
    "Dias sem movimentação": null,
    "Pendências": "Aguardando DCLC enviar o Processo para a SEMA corrigir",
    "Órgão Responsável pela pendência": "DCLC",
    "Engenheiro Responsável": "Nada consta",
    "Situação_1": "Licitação",
    "Área": "MEIO AMBIENTE"
  },
  {
    "Data Inicial": 44985,
    "Modalidade do Repasse": "Emenda",
    "Proposta/ Demanda": "010870/2023",
    "Termo de  Formalização": "Contrato de Repasse",
    "Número do Termo": 941152,
    "Data de Assinatura": 45100,
    "Ano": 2023,
    "Vigência": 46196,
    "Cláusula Suspensiva": 45595,
    "Esfera": "Federal",
    "Situação": "Assinado",
    "Parlamentar": "15810009 - Jefferson Campos ",
    "Partido Político": "PL",
    "Código da Emenda": 202315810009,
    "Função": "27 - Desporto e lazer",
    "Subfunção": "812 - Desporto comunitário",
    "Código da Receita": null,
    "Repasse": 544562.97,
    "Contrapartida": 5759.83,
    "Ministério": "Esporte",
    "Programa": "5100020230001 - Apoio à Implantação e Modernização de Infraestrutura para Esporte Educacional, Recreativo e de Lazer",
    "Objeto": "Reforma do Campo de Futebol do CERMAG",
    "Conta Bancária": "006.647055-8\n5741859328",
    "Valor Liberado": 544562.97,
    "Data do depósito": 45838,
    "Modalidade": "Concorrência Eletrônica",
    "Número/Ano": "16/2024",
    "Contrato nº": "010/2025",
    "Contratada": "DCA Engenharia e Construções Eireli-EPP",
    "Vigência do Contrato": "12 Meses a partir da Assinatura do Contrato",
    "Assinatura do Contrato": 45712,
    "Término da Vigência": 46077,
    "Aditamento de vigência": null,
    "Prazo de Execução": "90 D a partir da OIS",
    "Ordem de Início de Serviço": 45889,
    "Término da Execução": 45979,
    "Aditamento de Execução": null,
    "Valor do Contrato": 753948.26,
    "Ficha Orçamentária RP": null,
    "Nota de Empenho RP": null,
    "RP Vigente": 544562.97,
    "Ficha Orçamentária CP": null,
    "Nota de Empenho CP": "1318 -1319 -1370/2025",
    "CP Vigente": 46837.69,
    "Nota de Empenho Excl": null,
    "Ficha Orçamentária Excl": null,
    "CP Exclusiva/Recurso Próprio": 162547.6,
    "Aditamento de Valor": null,
    "CNO": "90.025.22966/73",
    "% Medição": 0.1686,
    "Valor Pago": null,
    "% Pago": 0,
    "Saldo de RP": 0,
    "Saldo na conta (rendimentos)": null,
    "Prestação de Contas": null,
    "Processo SPD": "3410/2023",
    "Processo Crédito Adicional": null,
    "Processo Licitatório": "790/2024",
    "Processo Medição": "213/2025",
    "Data da Última Medição/Movimentação": 45959,
    "Dias sem medição": null,
    "Dias sem movimentação": null,
    "Pendências": "Aguardando autorização do ordenador de despesa",
    "Órgão Responsável pela pendência": "SEF",
    "Engenheiro Responsável": "Adilson",
    "Situação_1": "Execução",
    "Área": "ESPORTE"
  },
  {
    "Data Inicial": 45072,
    "Modalidade do Repasse": "Emenda",
    "Proposta/ Demanda": "09032023-037404",
    "Termo de  Formalização": "Transferência Especial",
    "Número do Termo": "09032023-037404",
    "Data de Assinatura": 45265,
    "Ano": 2023,
    "Vigência": 46345,
    "Cláusula Suspensiva": null,
    "Esfera": "Federal",
    "Situação": "Assinado",
    "Parlamentar": "3977 - Enrico Misasi",
    "Partido Político": "MDB",
    "Código da Emenda": 202339770009,
    "Função": "28 - Encargos especiais",
    "Subfunção": "845 - Outras transferências",
    "Código da Receita": null,
    "Repasse": 200000,
    "Contrapartida": null,
    "Ministério": "Fazenda",
    "Programa": "Transferência Especial - Investimento",
    "Objeto": "Reforma de Quadra Esportiva no Parque São Luiz",
    "Conta Bancária": "6672007-4\n575858239-1",
    "Valor Liberado": 200000,
    "Data do depósito": 45272,
    "Modalidade": "Concorrência Eletrônica",
    "Número/Ano": "11/2024",
    "Contrato nº": "128/2024",
    "Contratada": "Construtora e Serralheria São José Ltda",
    "Vigência do Contrato": "12 Meses a partir da Assinatura do Contrato",
    "Assinatura do Contrato": 45657,
    "Término da Vigência": 46022,
    "Aditamento de vigência": null,
    "Prazo de Execução": "90 D a partir da OIS",
    "Ordem de Início de Serviço": null,
    "Término da Execução": null,
    "Aditamento de Execução": null,
    "Valor do Contrato": 178870,
    "Ficha Orçamentária RP": null,
    "Nota de Empenho RP": null,
    "RP Vigente": 178870,
    "Ficha Orçamentária CP": null,
    "Nota de Empenho CP": null,
    "CP Vigente": 26113.67,
    "Nota de Empenho Excl": null,
    "Ficha Orçamentária Excl": null,
    "CP Exclusiva/Recurso Próprio": null,
    "Aditamento de Valor": null,
    "CNO": null,
    "% Medição": null,
    "Valor Pago": null,
    "% Pago": null,
    "Saldo de RP": 21130,
    "Saldo na conta (rendimentos)": 33520.41,
    "Prestação de Contas": null,
    "Processo SPD": "4773/2023",
    "Processo Crédito Adicional": null,
    "Processo Licitatório": "709/2024",
    "Processo Medição": null,
    "Data da Última Medição/Movimentação": null,
    "Dias sem medição": null,
    "Dias sem movimentação": null,
    "Pendências": "Aguardando OIS e ampliação de meta",
    "Órgão Responsável pela pendência": "SOURB",
    "Engenheiro Responsável": "Adilson",
    "Situação_1": "Plano de Trabalho",
    "Área": "ESPORTE"
  },
  {
    "Data Inicial": 45141,
    "Modalidade do Repasse": "Transferência Voluntária",
    "Proposta/ Demanda": 62292,
    "Termo de  Formalização": "Convênio",
    "Número do Termo": 100882,
    "Data de Assinatura": 45425,
    "Ano": 2024,
    "Vigência": 46145,
    "Cláusula Suspensiva": null,
    "Esfera": "Estadual",
    "Situação": "Assinado",
    "Parlamentar": "Professora Bebel",
    "Partido Político": null,
    "Código da Emenda": "2023.073.50755",
    "Função": "15 - Urbanismo",
    "Subfunção": "451 - Infraestrutura Urbana ",
    "Código da Receita": null,
    "Repasse": 500000,
    "Contrapartida": 129674.9,
    "Ministério": "SGRI",
    "Programa": "Infraestrutura Urbana",
    "Objeto": "Troca de iluminação convencional por tecnologia LED no Bairro da Chave e Jardim Europa",
    "Conta Bancária": "40.842-5",
    "Valor Liberado": null,
    "Data do depósito": null,
    "Modalidade": "Concorrência Eletrônica",
    "Número/Ano": 45627,
    "Contrato nº": null,
    "Contratada": null,
    "Vigência do Contrato": null,
    "Assinatura do Contrato": null,
    "Término da Vigência": null,
    "Aditamento de vigência": null,
    "Prazo de Execução": null,
    "Ordem de Início de Serviço": null,
    "Término da Execução": null,
    "Aditamento de Execução": null,
    "Valor do Contrato": null,
    "Ficha Orçamentária RP": null,
    "Nota de Empenho RP": null,
    "RP Vigente": 500000,
    "Ficha Orçamentária CP": null,
    "Nota de Empenho CP": null,
    "CP Vigente": 122059.88,
    "Nota de Empenho Excl": null,
    "Ficha Orçamentária Excl": null,
    "CP Exclusiva/Recurso Próprio": null,
    "Aditamento de Valor": null,
    "CNO": null,
    "% Medição": null,
    "Valor Pago": null,
    "% Pago": null,
    "Saldo de RP": 0,
    "Saldo na conta (rendimentos)": null,
    "Prestação de Contas": null,
    "Processo SPD": "7096/2023",
    "Processo Crédito Adicional": "489/2024",
    "Processo Licitatório": "766/2024",
    "Processo Medição": null,
    "Data da Última Medição/Movimentação": null,
    "Dias sem medição": null,
    "Dias sem movimentação": null,
    "Pendências": "1. Aguardando análise do laudo técnico\n2. Alterar o responsável técnico ",
    "Órgão Responsável pela pendência": "SOURB",
    "Engenheiro Responsável": "Roberto",
    "Situação_1": "Licitação",
    "Área": "INFRAESTRUTURA"
  },
  {
    "Data Inicial": 45149,
    "Modalidade do Repasse": "Emenda",
    "Proposta/ Demanda": 62307,
    "Termo de  Formalização": "Convênio",
    "Número do Termo": 103279,
    "Data de Assinatura": 45288,
    "Ano": 2023,
    "Vigência": 46008,
    "Cláusula Suspensiva": null,
    "Esfera": "Estadual",
    "Situação": "Assinado",
    "Parlamentar": "Vitão do Cachorrão",
    "Partido Político": "REPUBLICANOS",
    "Código da Emenda": "2023.289.50909",
    "Função": "27 - Desporto e Lazer",
    "Subfunção": 813,
    "Código da Receita": null,
    "Repasse": 100000,
    "Contrapartida": 17239.08,
    "Ministério": "SGRI",
    "Programa": "Infraestrutura / Sistema de Lazer",
    "Objeto": "Construção de pista de caminhada na praça do Jardim São Lucas",
    "Conta Bancária": "40.841-7",
    "Valor Liberado": 100000,
    "Data do depósito": 45820,
    "Modalidade": "Concorrência Eletrônica",
    "Número/Ano": 45566,
    "Contrato nº": "009/2025",
    "Contratada": "DCA Engenharia e Construções Eireli - EPP",
    "Vigência do Contrato": "12 M a partir da assinatura do Contrato",
    "Assinatura do Contrato": 45712,
    "Término da Vigência": 46077,
    "Aditamento de vigência": null,
    "Prazo de Execução": "3 M a partir da OIS",
    "Ordem de Início de Serviço": 45742,
    "Término da Execução": 45832,
    "Aditamento de Execução": null,
    "Valor do Contrato": 116000,
    "Ficha Orçamentária RP": null,
    "Nota de Empenho RP": null,
    "RP Vigente": 100000,
    "Ficha Orçamentária CP": null,
    "Nota de Empenho CP": null,
    "CP Vigente": 16000,
    "Nota de Empenho Excl": null,
    "Ficha Orçamentária Excl": null,
    "CP Exclusiva/Recurso Próprio": null,
    "Aditamento de Valor": null,
    "CNO": null,
    "% Medição": null,
    "Valor Pago": 116000,
    "% Pago": 1,
    "Saldo de RP": 0,
    "Saldo na conta (rendimentos)": null,
    "Prestação de Contas": null,
    "Processo SPD": "7095/2023",
    "Processo Crédito Adicional": null,
    "Processo Licitatório": "_02/2024",
    "Processo Medição": null,
    "Data da Última Medição/Movimentação": null,
    "Dias sem medição": null,
    "Dias sem movimentação": null,
    "Pendências": "Aguardando docs para PC",
    "Órgão Responsável pela pendência": "SEF",
    "Engenheiro Responsável": "Fábio",
    "Situação_1": "Execução",
    "Área": "ESPORTE"
  },
  {
    "Data Inicial": 45208,
    "Modalidade do Repasse": "Programa",
    "Proposta/ Demanda": "26298009394/2023",
    "Termo de  Formalização": "Termo de Compromisso",
    "Número do Termo": 962647,
    "Data de Assinatura": 45531,
    "Ano": 2024,
    "Vigência": 46992,
    "Cláusula Suspensiva": 45621,
    "Esfera": "Federal",
    "Situação": "Assinado",
    "Parlamentar": null,
    "Partido Político": null,
    "Código da Emenda": null,
    "Função": null,
    "Subfunção": null,
    "Código da Receita": null,
    "Repasse": 5737882.19,
    "Contrapartida": 57958.41,
    "Ministério": "FNDE",
    "Programa": "2629820230005 - Novo PAC - Creches e Escolas de Educação Infantil",
    "Objeto": "Construção de Creche e Escola de Educação Infantil no Parque Santa Márcia",
    "Conta Bancária": "66470582\n574185935-2",
    "Valor Liberado": null,
    "Data do depósito": null,
    "Modalidade": "Concorrência Eletrônica",
    "Número/Ano": "004/2025",
    "Contrato nº": "087/2025",
    "Contratada": "Hype Construtora Ltda.",
    "Vigência do Contrato": null,
    "Assinatura do Contrato": null,
    "Término da Vigência": 46500,
    "Aditamento de vigência": null,
    "Prazo de Execução": null,
    "Ordem de Início de Serviço": null,
    "Término da Execução": null,
    "Aditamento de Execução": null,
    "Valor do Contrato": 5026580.9,
    "Ficha Orçamentária RP": null,
    "Nota de Empenho RP": null,
    "RP Vigente": 4621665.74,
    "Ficha Orçamentária CP": null,
    "Nota de Empenho CP": null,
    "CP Vigente": 46683.5,
    "Nota de Empenho Excl": null,
    "Ficha Orçamentária Excl": null,
    "CP Exclusiva/Recurso Próprio": 358231.66,
    "Aditamento de Valor": null,
    "CNO": null,
    "% Medição": null,
    "Valor Pago": null,
    "% Pago": null,
    "Saldo de RP": 0,
    "Saldo na conta (rendimentos)": null,
    "Prestação de Contas": null,
    "Processo SPD": "9558/2023",
    "Processo Crédito Adicional": "1064/2024",
    "Processo Licitatório": null,
    "Processo Medição": null,
    "Data da Última Medição/Movimentação": null,
    "Dias sem medição": null,
    "Dias sem movimentação": null,
    "Pendências": "1. Aguardando VRPL \n2. Aguardando propriedade da área\n3. Projeto de infraestrutura do entorno",
    "Órgão Responsável pela pendência": "1. GIGOV\n2. SENJ/SEED\n3. SOURB/SEMA",
    "Engenheiro Responsável": "Aline",
    "Situação_1": "Análide do VRPL pela GIGOV",
    "Área": "EDUCAÇÃO"
  },
  {
    "Data Inicial": 45208,
    "Modalidade do Repasse": "Programa",
    "Proposta/ Demanda": "36000008434/2023",
    "Termo de  Formalização": "InvestSUS",
    "Número do Termo": "11209.4720001/24-002",
    "Data de Assinatura": null,
    "Ano": 2023,
    "Vigência": null,
    "Cláusula Suspensiva": null,
    "Esfera": "Federal",
    "Situação": "Assinado",
    "Parlamentar": null,
    "Partido Político": null,
    "Código da Emenda": null,
    "Função": null,
    "Subfunção": null,
    "Código da Receita": null,
    "Repasse": 2435976.95,
    "Contrapartida": null,
    "Ministério": "SAÚDE",
    "Programa": "3600020230050 - Novo PAC - Unidades Básicas de Saúde",
    "Objeto": "Construção de UBS no Bairro Vossoroca",
    "Conta Bancária": null,
    "Valor Liberado": null,
    "Data do depósito": null,
    "Modalidade": "Concorrência Eletrônica",
    "Número/Ano": "003/2025",
    "Contrato nº": "66/2025",
    "Contratada": "Novos Negócios Comércio e Transporte Ltda.",
    "Vigência do Contrato": "12 Meses a partir da Assinatura do Contrato",
    "Assinatura do Contrato": 45884,
    "Término da Vigência": 46249,
    "Aditamento de vigência": null,
    "Prazo de Execução": "360 D a partir da OIS",
    "Ordem de Início de Serviço": 45884,
    "Término da Execução": 46244,
    "Aditamento de Execução": null,
    "Valor do Contrato": 1997393.7,
    "Ficha Orçamentária RP": null,
    "Nota de Empenho RP": null,
    "RP Vigente": null,
    "Ficha Orçamentária CP": null,
    "Nota de Empenho CP": null,
    "CP Vigente": null,
    "Nota de Empenho Excl": null,
    "Ficha Orçamentária Excl": null,
    "CP Exclusiva/Recurso Próprio": null,
    "Aditamento de Valor": null,
    "CNO": null,
    "% Medição": null,
    "Valor Pago": null,
    "% Pago": null,
    "Saldo de RP": 0,
    "Saldo na conta (rendimentos)": null,
    "Prestação de Contas": null,
    "Processo SPD": null,
    "Processo Crédito Adicional": null,
    "Processo Licitatório": "1604/2023",
    "Processo Medição": null,
    "Data da Última Medição/Movimentação": null,
    "Dias sem medição": null,
    "Dias sem movimentação": null,
    "Pendências": "Em início de execução",
    "Órgão Responsável pela pendência": "SOURB",
    "Engenheiro Responsável": "Aline",
    "Situação_1": null,
    "Área": "SAÚDE"
  },
  {
    "Data Inicial": 45216,
    "Modalidade do Repasse": "Programa",
    "Proposta/ Demanda": 63953,
    "Termo de  Formalização": "Convênio",
    "Número do Termo": 175,
    "Data de Assinatura": 45280,
    "Ano": 2023,
    "Vigência": 46360,
    "Cláusula Suspensiva": null,
    "Esfera": "Estadual",
    "Situação": "Assinado",
    "Parlamentar": null,
    "Partido Político": null,
    "Código da Emenda": null,
    "Função": null,
    "Subfunção": null,
    "Código da Receita": null,
    "Repasse": 571081.63,
    "Contrapartida": 21332.65,
    "Ministério": "Turismo",
    "Programa": "MIT - Município de Interesse Turístico de Votorantim - 584 - Infraestrutura Turística",
    "Objeto": "Construção do Centro de Atendimento do Turismo",
    "Conta Bancária": "41.151-5",
    "Valor Liberado": 285540.81,
    "Data do depósito": 45805,
    "Modalidade": "Concorrência Eletrônica",
    "Número/Ano": "002/2025",
    "Contrato nº": "037/2025",
    "Contratada": "Novos Negócios Comércio e Transporte Ltda.",
    "Vigência do Contrato": "12 Meses a partir da Assinatura do Contrato",
    "Assinatura do Contrato": 45772,
    "Término da Vigência": 46137,
    "Aditamento de vigência": null,
    "Prazo de Execução": "05 M a partir da OIS",
    "Ordem de Início de Serviço": 45791,
    "Término da Execução": 45944,
    "Aditamento de Execução": null,
    "Valor do Contrato": 513547.08,
    "Ficha Orçamentária RP": null,
    "Nota de Empenho RP": null,
    "RP Vigente": 437743.25,
    "Ficha Orçamentária CP": null,
    "Nota de Empenho CP": null,
    "CP Vigente": 75803.83,
    "Nota de Empenho Excl": null,
    "Ficha Orçamentária Excl": null,
    "CP Exclusiva/Recurso Próprio": null,
    "Aditamento de Valor": null,
    "CNO": null,
    "% Medição": null,
    "Valor Pago": null,
    "% Pago": null,
    "Saldo de RP": 285540.81,
    "Saldo na conta (rendimentos)": null,
    "Prestação de Contas": null,
    "Processo SPD": "9059/2023",
    "Processo Crédito Adicional": null,
    "Processo Licitatório": "630/2024",
    "Processo Medição": null,
    "Data da Última Medição/Movimentação": null,
    "Dias sem medição": null,
    "Dias sem movimentação": null,
    "Pendências": "Aguardando abertura de matrícula no Cartório de Votorantim ",
    "Órgão Responsável pela pendência": "SPD/SOURB/SENJ",
    "Engenheiro Responsável": "Fábio",
    "Situação_1": null,
    "Área": "TURISMO"
  },
  {
    "Data Inicial": 45254,
    "Modalidade do Repasse": "Emenda",
    "Proposta/ Demanda": "065119\n095322",
    "Termo de  Formalização": "Convênio",
    "Número do Termo": "172/2024",
    "Data de Assinatura": 45453,
    "Ano": 2023,
    "Vigência": 46183,
    "Cláusula Suspensiva": null,
    "Esfera": "Estadual",
    "Situação": "Assinado",
    "Parlamentar": "Delegado Olim",
    "Partido Político": "PROGRESSISTAS",
    "Código da Emenda": "2023.032.51620",
    "Função": "27 - Desporto e Lazer",
    "Subfunção": "812 - Desporto Comunitário",
    "Código da Receita": null,
    "Repasse": 200000,
    "Contrapartida": 22184.95,
    "Ministério": "Esporte",
    "Programa": "Obras Esportivas",
    "Objeto": "Reforma do ginásio poliesportivo do Jardim Residencial Altos de Votorantim",
    "Conta Bancária": "41.041-1",
    "Valor Liberado": 200000,
    "Data do depósito": 45789,
    "Modalidade": "Concorrência Eletrônica",
    "Número/Ano": "001/2025",
    "Contrato nº": "034/2025",
    "Contratada": "Construtora e Serralheria São José Ltda",
    "Vigência do Contrato": "12 Meses a partir da Assinatura do Contrato",
    "Assinatura do Contrato": 45757,
    "Término da Vigência": 46122,
    "Aditamento de vigência": null,
    "Prazo de Execução": "03 M a partir da OIS",
    "Ordem de Início de Serviço": 45769,
    "Término da Execução": 45859,
    "Aditamento de Execução": 45950,
    "Valor do Contrato": 263719.89,
    "Ficha Orçamentária RP": null,
    "Nota de Empenho RP": null,
    "RP Vigente": 200000,
    "Ficha Orçamentária CP": null,
    "Nota de Empenho CP": null,
    "CP Vigente": 63719.89,
    "Nota de Empenho Excl": null,
    "Ficha Orçamentária Excl": null,
    "CP Exclusiva/Recurso Próprio": null,
    "Aditamento de Valor": 82975.43,
    "CNO": null,
    "% Medição": 0.8366,
    "Valor Pago": 151204.47,
    "% Pago": 0.573352544626042,
    "Saldo de RP": 0,
    "Saldo na conta (rendimentos)": null,
    "Prestação de Contas": null,
    "Processo SPD": "807/2024",
    "Processo Crédito Adicional": "808/2024",
    "Processo Licitatório": "1112/2024",
    "Processo Medição": "584/2025",
    "Data da Última Medição/Movimentação": 45819,
    "Dias sem medição": null,
    "Dias sem movimentação": null,
    "Pendências": "Aguardando Processo para pagamento",
    "Órgão Responsável pela pendência": "SEF",
    "Engenheiro Responsável": "Fábio",
    "Situação_1": "Aditamento de valor",
    "Área": "ESPORTE"
  },
  {
    "Data Inicial": 45265,
    "Modalidade do Repasse": "Programa",
    "Proposta/ Demanda": 65350,
    "Termo de  Formalização": "Convênio",
    "Número do Termo": 101131,
    "Data de Assinatura": 45429,
    "Ano": 2023,
    "Vigência": 46149,
    "Cláusula Suspensiva": null,
    "Esfera": "Estadual",
    "Situação": "Assinado",
    "Parlamentar": null,
    "Partido Político": null,
    "Código da Emenda": null,
    "Função": null,
    "Subfunção": null,
    "Código da Receita": null,
    "Repasse": 1500000,
    "Contrapartida": 0,
    "Ministério": "SGRI",
    "Programa": "674 - Infraestrutura Urbana",
    "Objeto": "Troca de Iluminação Convencional por tecnologia LED na Vila Domingues, Jardim Mirante dos Ovnis, Jardim Clarice e adjacência",
    "Conta Bancária": "41.269-4",
    "Valor Liberado": null,
    "Data do depósito": null,
    "Modalidade": "Concorrência Eletrônica",
    "Número/Ano": 45627,
    "Contrato nº": null,
    "Contratada": null,
    "Vigência do Contrato": null,
    "Assinatura do Contrato": null,
    "Término da Vigência": null,
    "Aditamento de vigência": null,
    "Prazo de Execução": null,
    "Ordem de Início de Serviço": null,
    "Término da Execução": null,
    "Aditamento de Execução": null,
    "Valor do Contrato": null,
    "Ficha Orçamentária RP": null,
    "Nota de Empenho RP": null,
    "RP Vigente": 1497961.99,
    "Ficha Orçamentária CP": null,
    "Nota de Empenho CP": null,
    "CP Vigente": 0,
    "Nota de Empenho Excl": null,
    "Ficha Orçamentária Excl": null,
    "CP Exclusiva/Recurso Próprio": null,
    "Aditamento de Valor": null,
    "CNO": null,
    "% Medição": null,
    "Valor Pago": null,
    "% Pago": null,
    "Saldo de RP": 0,
    "Saldo na conta (rendimentos)": null,
    "Prestação de Contas": null,
    "Processo SPD": "10120/2023",
    "Processo Crédito Adicional": "490/2024",
    "Processo Licitatório": "766/2024",
    "Processo Medição": null,
    "Data da Última Medição/Movimentação": null,
    "Dias sem medição": null,
    "Dias sem movimentação": null,
    "Pendências": "1. Aguardando análise do laudo técnico\n2. Alterar o responsável técnico ",
    "Órgão Responsável pela pendência": "SOURB",
    "Engenheiro Responsável": "Saulo",
    "Situação_1": "Licitação",
    "Área": "INFRAESTRUTURA"
  },
  {
    "Data Inicial": 45265,
    "Modalidade do Repasse": "Programa",
    "Proposta/ Demanda": 71089,
    "Termo de  Formalização": "Contrato de Repasse",
    "Número do Termo": 953845,
    "Data de Assinatura": 45289,
    "Ano": 2023,
    "Vigência": 46385,
    "Cláusula Suspensiva": 45559,
    "Esfera": "Federal",
    "Situação": "Assinado",
    "Parlamentar": "Jilmar Tatto",
    "Partido Político": "PT",
    "Código da Emenda": null,
    "Função": null,
    "Subfunção": null,
    "Código da Receita": null,
    "Repasse": 481104,
    "Contrapartida": 42816.68,
    "Ministério": "Cidades",
    "Programa": "Programa 2219 - Acao 00T1 - Apoio a Politica Nacional de Desenvolvimento Urbano Voltado a Implantacao e Qualificacao Viaria - RP2",
    "Objeto": "Recapeamento asfáltico no Município de Votorantim/SP (Avenida Gisele Constantino) - Trecho 1",
    "Conta Bancária": "66470566\n 574185933-6",
    "Valor Liberado": "336.772,80\n144.331,20",
    "Data do depósito": "04/09/2025\n10/12/2025",
    "Modalidade": "Concorrência Eletrônica",
    "Número/Ano": "15/2024",
    "Contrato nº": "013/2025",
    "Contratada": "Céu Azul Terraplanagem e Pavimentadora Ltda.",
    "Vigência do Contrato": "12 Meses a partir da Assinatura do Contrato",
    "Assinatura do Contrato": 45714,
    "Término da Vigência": 46079,
    "Aditamento de vigência": null,
    "Prazo de Execução": "60 D a partir da OIS",
    "Ordem de Início de Serviço": null,
    "Término da Execução": null,
    "Aditamento de Execução": null,
    "Valor do Contrato": 386454.26,
    "Ficha Orçamentária RP": null,
    "Nota de Empenho RP": null,
    "RP Vigente": 382473.78,
    "Ficha Orçamentária CP": null,
    "Nota de Empenho CP": null,
    "CP Vigente": 3980.48,
    "Nota de Empenho Excl": null,
    "Ficha Orçamentária Excl": null,
    "CP Exclusiva/Recurso Próprio": null,
    "Aditamento de Valor": null,
    "CNO": null,
    "% Medição": null,
    "Valor Pago": null,
    "% Pago": null,
    "Saldo de RP": 98630.22,
    "Saldo na conta (rendimentos)": null,
    "Prestação de Contas": null,
    "Processo SPD": "003/2024",
    "Processo Crédito Adicional": null,
    "Processo Licitatório": "1106/2024",
    "Processo Medição": null,
    "Data da Última Medição/Movimentação": null,
    "Dias sem medição": null,
    "Dias sem movimentação": null,
    "Pendências": "1. Aguardando OIS \n2. Verificar utilização de saldo",
    "Órgão Responsável pela pendência": "1. SOURB\n2. SPD",
    "Engenheiro Responsável": "Adilson",
    "Situação_1": "Início de obra",
    "Área": "INFRAESTRUTURA"
  },
  {
    "Data Inicial": 45282,
    "Modalidade do Repasse": "Programa",
    "Proposta/ Demanda": 72585,
    "Termo de  Formalização": "Contrato de Repasse",
    "Número do Termo": 954658,
    "Data de Assinatura": 45289,
    "Ano": 2023,
    "Vigência": 46385,
    "Cláusula Suspensiva": 45559,
    "Esfera": "Federal",
    "Situação": "Assinado",
    "Parlamentar": "Jilmar Tatto",
    "Partido Político": "PT",
    "Código da Emenda": null,
    "Função": null,
    "Subfunção": null,
    "Código da Receita": null,
    "Repasse": 481104,
    "Contrapartida": 81049.38,
    "Ministério": "Cidades",
    "Programa": "Programa 2219 - Acao 00T1 - Apoio a Politica Nacional de Desenvolvimento Urbano Voltado a Implantacao e Qualificacao Viaria - RP2",
    "Objeto": "Recapeamento asfáltico no Município de Votorantim/SP (Avenida Gisele Constantino) - Trecho 2",
    "Conta Bancária": "66470574\n574185934-4",
    "Valor Liberado": "336.772,80\n144.331,20",
    "Data do depósito": "04/09/2025\n10/12/2025",
    "Modalidade": "Concorrência Eletrônica",
    "Número/Ano": "15/2024",
    "Contrato nº": "013/2025",
    "Contratada": "Céu Azul Terraplanagem e Pavimentadora Ltda.",
    "Vigência do Contrato": "12 Meses a partir da Assinatura do Contrato",
    "Assinatura do Contrato": 45714,
    "Término da Vigência": 46079,
    "Aditamento de vigência": null,
    "Prazo de Execução": "60 D a partir da OIS",
    "Ordem de Início de Serviço": null,
    "Término da Execução": null,
    "Aditamento de Execução": null,
    "Valor do Contrato": 529407.07,
    "Ficha Orçamentária RP": null,
    "Nota de Empenho RP": null,
    "RP Vigente": 408925.6,
    "Ficha Orçamentária CP": null,
    "Nota de Empenho CP": null,
    "CP Vigente": 4255.77,
    "Nota de Empenho Excl": null,
    "Ficha Orçamentária Excl": null,
    "CP Exclusiva/Recurso Próprio": 116225.7,
    "Aditamento de Valor": null,
    "CNO": null,
    "% Medição": null,
    "Valor Pago": null,
    "% Pago": null,
    "Saldo de RP": 72178.4,
    "Saldo na conta (rendimentos)": null,
    "Prestação de Contas": null,
    "Processo SPD": "004/2024",
    "Processo Crédito Adicional": null,
    "Processo Licitatório": "1106/2024",
    "Processo Medição": null,
    "Data da Última Medição/Movimentação": null,
    "Dias sem medição": null,
    "Dias sem movimentação": null,
    "Pendências": "1. Aguardando OIS \n2. Verificar utilização de saldo",
    "Órgão Responsável pela pendência": "1. SOURB\n2. SPD",
    "Engenheiro Responsável": "Adilson",
    "Situação_1": "Início de obra",
    "Área": "INFRAESTRUTURA"
  },
  {
    "Data Inicial": 45362,
    "Modalidade do Repasse": "Emenda",
    "Proposta/ Demanda": 2318,
    "Termo de  Formalização": "Convênio",
    "Número do Termo": 961721,
    "Data de Assinatura": 45653,
    "Ano": 2024,
    "Vigência": 46373,
    "Cláusula Suspensiva": 46197,
    "Esfera": "Federal",
    "Situação": "Cláusula Suspensiva",
    "Parlamentar": "15810017 - Jefferson Campos ",
    "Partido Político": null,
    "Código da Emenda": 202415810017,
    "Função": 97,
    "Subfunção": 812,
    "Código da Receita": null,
    "Repasse": 300000,
    "Contrapartida": 15000,
    "Ministério": "Esporte",
    "Programa": "Desenvolvimento de Atividades e Apoio a Programas e Projetos de Esporte Amador, Educacao, Lazer e Inclusao Social - SNEAELIS (Emenda Parlamentar Individual - RP6 - Convênio)",
    "Objeto": "Desenvolvimento do Projeto Esportivo no Município de Votorantim/SP",
    "Conta Bancária": "6071018-2\n 574185928-0",
    "Valor Liberado": null,
    "Data do depósito": null,
    "Modalidade": null,
    "Número/Ano": null,
    "Contrato nº": null,
    "Contratada": null,
    "Vigência do Contrato": null,
    "Assinatura do Contrato": null,
    "Término da Vigência": null,
    "Aditamento de vigência": null,
    "Prazo de Execução": null,
    "Ordem de Início de Serviço": null,
    "Término da Execução": null,
    "Aditamento de Execução": null,
    "Valor do Contrato": null,
    "Ficha Orçamentária RP": null,
    "Nota de Empenho RP": null,
    "RP Vigente": null,
    "Ficha Orçamentária CP": null,
    "Nota de Empenho CP": null,
    "CP Vigente": null,
    "Nota de Empenho Excl": null,
    "Ficha Orçamentária Excl": null,
    "CP Exclusiva/Recurso Próprio": null,
    "Aditamento de Valor": null,
    "CNO": null,
    "% Medição": null,
    "Valor Pago": null,
    "% Pago": null,
    "Saldo de RP": 0,
    "Saldo na conta (rendimentos)": null,
    "Prestação de Contas": null,
    "Processo SPD": "684/2024",
    "Processo Crédito Adicional": null,
    "Processo Licitatório": null,
    "Processo Medição": null,
    "Data da Última Medição/Movimentação": null,
    "Dias sem medição": null,
    "Dias sem movimentação": null,
    "Pendências": "Análise da Planilha de Custo suspensa pelo MESP. Retoma em janeiro/2026.",
    "Órgão Responsável pela pendência": "MESP",
    "Engenheiro Responsável": null,
    "Situação_1": "Cláusula Suspensiva",
    "Área": "ESPORTE"
  },
  {
    "Data Inicial": 45376,
    "Modalidade do Repasse": "Transferência Voluntária",
    "Proposta/ Demanda": 72316,
    "Termo de  Formalização": "Convênio",
    "Número do Termo": "211/2025",
    "Data de Assinatura": 45966,
    "Ano": 2025,
    "Vigência": 46354,
    "Cláusula Suspensiva": null,
    "Esfera": "Estadual",
    "Situação": "Assinado",
    "Parlamentar": "Delegado da Cunha",
    "Partido Político": null,
    "Código da Emenda": "2024.313.53517",
    "Função": "06 - Segurança Pública",
    "Subfunção": "181 - Policiamento",
    "Código da Receita": null,
    "Repasse": 100000,
    "Contrapartida": 15312.84,
    "Ministério": "SSP",
    "Programa": "462 - Aquisição de equipamentos da SSP",
    "Objeto": "Aquisição de equipamentos GCM",
    "Conta Bancária": "42.041-7",
    "Valor Liberado": null,
    "Data do depósito": null,
    "Modalidade": null,
    "Número/Ano": null,
    "Contrato nº": null,
    "Contratada": null,
    "Vigência do Contrato": null,
    "Assinatura do Contrato": null,
    "Término da Vigência": null,
    "Aditamento de vigência": null,
    "Prazo de Execução": null,
    "Ordem de Início de Serviço": null,
    "Término da Execução": null,
    "Aditamento de Execução": null,
    "Valor do Contrato": null,
    "Ficha Orçamentária RP": null,
    "Nota de Empenho RP": null,
    "RP Vigente": null,
    "Ficha Orçamentária CP": null,
    "Nota de Empenho CP": null,
    "CP Vigente": null,
    "Nota de Empenho Excl": null,
    "Ficha Orçamentária Excl": null,
    "CP Exclusiva/Recurso Próprio": null,
    "Aditamento de Valor": null,
    "CNO": null,
    "% Medição": null,
    "Valor Pago": null,
    "% Pago": null,
    "Saldo de RP": 0,
    "Saldo na conta (rendimentos)": null,
    "Prestação de Contas": null,
    "Processo SPD": "167/2024",
    "Processo Crédito Adicional": null,
    "Processo Licitatório": null,
    "Processo Medição": null,
    "Data da Última Medição/Movimentação": null,
    "Dias sem medição": null,
    "Dias sem movimentação": null,
    "Pendências": "1. Processo Licitatório/Cotação de Preços\n2. Aguardando liberação do repasse",
    "Órgão Responsável pela pendência": "1. DCLC\n2. SSP",
    "Engenheiro Responsável": null,
    "Situação_1": null,
    "Área": "SEGURANÇA"
  },
  {
    "Data Inicial": 45398,
    "Modalidade do Repasse": "Emenda",
    "Proposta/ Demanda": 72949,
    "Termo de  Formalização": "Convênio",
    "Número do Termo": "SEDUC-PRC-2024-01102-DM",
    "Data de Assinatura": 45644,
    "Ano": 2024,
    "Vigência": 46008,
    "Cláusula Suspensiva": null,
    "Esfera": "Estadual",
    "Situação": "Assinado",
    "Parlamentar": "Luiz Fernando T Ferreira",
    "Partido Político": null,
    "Código da Emenda": null,
    "Função": null,
    "Subfunção": null,
    "Código da Receita": null,
    "Repasse": 200000,
    "Contrapartida": 19199.66,
    "Ministério": "Educação",
    "Programa": "746 - (CONVÊNIO) Infraestrutura Física",
    "Objeto": "Revitalização da Quadra Poliesportiva, localizada no conjunto da CMEI Raphaela Resio Cau, Rua Carlos Caldini, 300 - Vila Garcia ",
    "Conta Bancária": "42042-5",
    "Valor Liberado": null,
    "Data do depósito": null,
    "Modalidade": null,
    "Número/Ano": null,
    "Contrato nº": null,
    "Contratada": null,
    "Vigência do Contrato": null,
    "Assinatura do Contrato": null,
    "Término da Vigência": null,
    "Aditamento de vigência": null,
    "Prazo de Execução": null,
    "Ordem de Início de Serviço": null,
    "Término da Execução": null,
    "Aditamento de Execução": null,
    "Valor do Contrato": null,
    "Ficha Orçamentária RP": null,
    "Nota de Empenho RP": null,
    "RP Vigente": null,
    "Ficha Orçamentária CP": null,
    "Nota de Empenho CP": null,
    "CP Vigente": null,
    "Nota de Empenho Excl": null,
    "Ficha Orçamentária Excl": null,
    "CP Exclusiva/Recurso Próprio": null,
    "Aditamento de Valor": null,
    "CNO": null,
    "% Medição": null,
    "Valor Pago": null,
    "% Pago": null,
    "Saldo de RP": 0,
    "Saldo na conta (rendimentos)": null,
    "Prestação de Contas": null,
    "Processo SPD": "272/2024",
    "Processo Crédito Adicional": null,
    "Processo Licitatório": null,
    "Processo Medição": null,
    "Data da Última Medição/Movimentação": null,
    "Dias sem medição": null,
    "Dias sem movimentação": null,
    "Pendências": "1. CND Estadual Positiva\n2. Em análise administrativa ARINS\n3. Convênio vence em dezembro de 2025",
    "Órgão Responsável pela pendência": "1. SEA\n2. SEESP\n3. SPD/SEED",
    "Engenheiro Responsável": "Fábio",
    "Situação_1": null,
    "Área": "EDUCAÇÃO"
  },
  {
    "Data Inicial": 45698,
    "Modalidade do Repasse": "Emenda",
    "Proposta/ Demanda": 85086,
    "Termo de  Formalização": "Convênio",
    "Número do Termo": 100568,
    "Data de Assinatura": 45933,
    "Ano": 2025,
    "Vigência": 46663,
    "Cláusula Suspensiva": null,
    "Esfera": "Estadual",
    "Situação": "Assinado",
    "Parlamentar": "Jorge Wilson Xerife do Consumidor",
    "Partido Político": null,
    "Código da Emenda": "2025.053.68773",
    "Função": "15 - Urbanismo",
    "Subfunção": "451 - Infraestrutura Urbana ",
    "Código da Receita": null,
    "Repasse": 400000,
    "Contrapartida": 12751.04,
    "Ministério": "SGRI",
    "Programa": "674 - Infraestrutura Urbana e Obras para Melhoria do Município",
    "Objeto": "Recapeamento asfáltico da Avenida Vitório Zancheta",
    "Conta Bancária": "45073-1",
    "Valor Liberado": null,
    "Data do depósito": null,
    "Modalidade": null,
    "Número/Ano": null,
    "Contrato nº": null,
    "Contratada": null,
    "Vigência do Contrato": null,
    "Assinatura do Contrato": null,
    "Término da Vigência": null,
    "Aditamento de vigência": null,
    "Prazo de Execução": null,
    "Ordem de Início de Serviço": null,
    "Término da Execução": null,
    "Aditamento de Execução": null,
    "Valor do Contrato": null,
    "Ficha Orçamentária RP": null,
    "Nota de Empenho RP": null,
    "RP Vigente": null,
    "Ficha Orçamentária CP": null,
    "Nota de Empenho CP": null,
    "CP Vigente": null,
    "Nota de Empenho Excl": null,
    "Ficha Orçamentária Excl": null,
    "CP Exclusiva/Recurso Próprio": null,
    "Aditamento de Valor": null,
    "CNO": null,
    "% Medição": null,
    "Valor Pago": null,
    "% Pago": null,
    "Saldo de RP": 0,
    "Saldo na conta (rendimentos)": null,
    "Prestação de Contas": null,
    "Processo SPD": "159/2025",
    "Processo Crédito Adicional": "1678/2025",
    "Processo Licitatório": null,
    "Processo Medição": null,
    "Data da Última Medição/Movimentação": null,
    "Dias sem medição": null,
    "Dias sem movimentação": null,
    "Pendências": "Em elaboração do ETP e despacho para o DCLC - Processo Licitatório FEDERAL e ESTADUAL",
    "Órgão Responsável pela pendência": "SOURB / SPD",
    "Engenheiro Responsável": "Adilson",
    "Situação_1": null,
    "Área": "INFRAESTRUTURA"
  },
  {
    "Data Inicial": 45700,
    "Modalidade do Repasse": "Emenda",
    "Proposta/ Demanda": 85715,
    "Termo de  Formalização": "Convênio",
    "Número do Termo": "SDUH-PRC-2025-00002-DM",
    "Data de Assinatura": 45986,
    "Ano": 2025,
    "Vigência": 46351,
    "Cláusula Suspensiva": null,
    "Esfera": "Estadual",
    "Situação": "Assinado",
    "Parlamentar": "Luiz Fernando T Ferreira",
    "Partido Político": "PT",
    "Código da Emenda": "2025.058.67945",
    "Função": "15 - Urbanismo",
    "Subfunção": "451 - Infraestrutura Urbana ",
    "Código da Receita": null,
    "Repasse": 200000,
    "Contrapartida": 50265.1,
    "Ministério": "SDUH",
    "Programa": "764 - Obras de Infraestrutura Urbana",
    "Objeto": "Reforma da praça do Conj. Habitacional Dr. Eliseu Vieira Rodrigues",
    "Conta Bancária": "45074-X",
    "Valor Liberado": null,
    "Data do depósito": null,
    "Modalidade": null,
    "Número/Ano": null,
    "Contrato nº": null,
    "Contratada": null,
    "Vigência do Contrato": null,
    "Assinatura do Contrato": null,
    "Término da Vigência": null,
    "Aditamento de vigência": null,
    "Prazo de Execução": null,
    "Ordem de Início de Serviço": null,
    "Término da Execução": null,
    "Aditamento de Execução": null,
    "Valor do Contrato": null,
    "Ficha Orçamentária RP": null,
    "Nota de Empenho RP": null,
    "RP Vigente": null,
    "Ficha Orçamentária CP": null,
    "Nota de Empenho CP": null,
    "CP Vigente": null,
    "Nota de Empenho Excl": null,
    "Ficha Orçamentária Excl": null,
    "CP Exclusiva/Recurso Próprio": null,
    "Aditamento de Valor": null,
    "CNO": null,
    "% Medição": null,
    "Valor Pago": null,
    "% Pago": null,
    "Saldo de RP": 0,
    "Saldo na conta (rendimentos)": null,
    "Prestação de Contas": null,
    "Processo SPD": "161/2025",
    "Processo Crédito Adicional": "1681/2025",
    "Processo Licitatório": null,
    "Processo Medição": null,
    "Data da Última Medição/Movimentação": null,
    "Dias sem medição": null,
    "Dias sem movimentação": null,
    "Pendências": "Aguardando processo licitatório",
    "Órgão Responsável pela pendência": "SOURB",
    "Engenheiro Responsável": "Adilson",
    "Situação_1": null,
    "Área": "INFRAESTRUTURA"
  },
  {
    "Data Inicial": 45734,
    "Modalidade do Repasse": "Emenda",
    "Proposta/ Demanda": 90120,
    "Termo de  Formalização": null,
    "Número do Termo": null,
    "Data de Assinatura": null,
    "Ano": 2025,
    "Vigência": null,
    "Cláusula Suspensiva": null,
    "Esfera": "Estadual",
    "Situação": "Proposta",
    "Parlamentar": "Delegado Olim",
    "Partido Político": null,
    "Código da Emenda": "2025.032.69363",
    "Função": null,
    "Subfunção": null,
    "Código da Receita": null,
    "Repasse": 400000,
    "Contrapartida": null,
    "Ministério": "Educação",
    "Programa": "679 - Equipamentos - Aquisição de equipamentos, materiais e bens diversos",
    "Objeto": "Itens e Bens Diversos - Mobiliário Administrativo e Mobiliário Sala de Aula",
    "Conta Bancária": null,
    "Valor Liberado": null,
    "Data do depósito": null,
    "Modalidade": null,
    "Número/Ano": null,
    "Contrato nº": null,
    "Contratada": null,
    "Vigência do Contrato": null,
    "Assinatura do Contrato": null,
    "Término da Vigência": null,
    "Aditamento de vigência": null,
    "Prazo de Execução": null,
    "Ordem de Início de Serviço": null,
    "Término da Execução": null,
    "Aditamento de Execução": null,
    "Valor do Contrato": null,
    "Ficha Orçamentária RP": null,
    "Nota de Empenho RP": null,
    "RP Vigente": null,
    "Ficha Orçamentária CP": null,
    "Nota de Empenho CP": null,
    "CP Vigente": null,
    "Nota de Empenho Excl": null,
    "Ficha Orçamentária Excl": null,
    "CP Exclusiva/Recurso Próprio": null,
    "Aditamento de Valor": null,
    "CNO": null,
    "% Medição": null,
    "Valor Pago": null,
    "% Pago": null,
    "Saldo de RP": 0,
    "Saldo na conta (rendimentos)": null,
    "Prestação de Contas": null,
    "Processo SPD": null,
    "Processo Crédito Adicional": null,
    "Processo Licitatório": null,
    "Processo Medição": null,
    "Data da Última Medição/Movimentação": null,
    "Dias sem medição": null,
    "Dias sem movimentação": null,
    "Pendências": "Aguardando crédito",
    "Órgão Responsável pela pendência": "SEDUC",
    "Engenheiro Responsável": null,
    "Situação_1": null,
    "Área": "EDUCAÇÃO"
  },
  {
    "Data Inicial": 45770,
    "Modalidade do Repasse": "Programa",
    "Proposta/ Demanda": 55732,
    "Termo de  Formalização": null,
    "Número do Termo": null,
    "Data de Assinatura": null,
    "Ano": 2025,
    "Vigência": null,
    "Cláusula Suspensiva": null,
    "Esfera": "Federal",
    "Situação": "Proposta",
    "Parlamentar": null,
    "Partido Político": null,
    "Código da Emenda": null,
    "Função": null,
    "Subfunção": null,
    "Código da Receita": null,
    "Repasse": 631528.48,
    "Contrapartida": 0,
    "Ministério": "MAPA",
    "Programa": "2200020250003 - Programa Nacional de Modernização e Apoio à Produção Agrícola - PROMAQ",
    "Objeto": "Aquisição de caminhão plataforma",
    "Conta Bancária": null,
    "Valor Liberado": null,
    "Data do depósito": null,
    "Modalidade": null,
    "Número/Ano": null,
    "Contrato nº": null,
    "Contratada": null,
    "Vigência do Contrato": null,
    "Assinatura do Contrato": null,
    "Término da Vigência": null,
    "Aditamento de vigência": null,
    "Prazo de Execução": null,
    "Ordem de Início de Serviço": null,
    "Término da Execução": null,
    "Aditamento de Execução": null,
    "Valor do Contrato": null,
    "Ficha Orçamentária RP": null,
    "Nota de Empenho RP": null,
    "RP Vigente": null,
    "Ficha Orçamentária CP": null,
    "Nota de Empenho CP": null,
    "CP Vigente": null,
    "Nota de Empenho Excl": null,
    "Ficha Orçamentária Excl": null,
    "CP Exclusiva/Recurso Próprio": null,
    "Aditamento de Valor": null,
    "CNO": null,
    "% Medição": null,
    "Valor Pago": null,
    "% Pago": null,
    "Saldo de RP": 0,
    "Saldo na conta (rendimentos)": null,
    "Prestação de Contas": null,
    "Processo SPD": null,
    "Processo Crédito Adicional": null,
    "Processo Licitatório": null,
    "Processo Medição": null,
    "Data da Última Medição/Movimentação": null,
    "Dias sem medição": null,
    "Dias sem movimentação": null,
    "Pendências": "Aguardando análise da proposta",
    "Órgão Responsável pela pendência": "MAPA",
    "Engenheiro Responsável": null,
    "Situação_1": null,
    "Área": "PRODUÇÃO AGRÍCOLA"
  },
  {
    "Data Inicial": 45770,
    "Modalidade do Repasse": "Programa",
    "Proposta/ Demanda": 55921,
    "Termo de  Formalização": null,
    "Número do Termo": null,
    "Data de Assinatura": null,
    "Ano": 2025,
    "Vigência": null,
    "Cláusula Suspensiva": null,
    "Esfera": "Federal",
    "Situação": "Proposta",
    "Parlamentar": null,
    "Partido Político": null,
    "Código da Emenda": null,
    "Função": null,
    "Subfunção": null,
    "Código da Receita": null,
    "Repasse": 21874034.91,
    "Contrapartida": 220949.85,
    "Ministério": null,
    "Programa": "2200020250004 - Programa Nacional de Estradas Rurais - PRONER",
    "Objeto": "Obras de Pavimentação de estrada vicinal no Município de Votorantim/SP (Estrada do Carafá)",
    "Conta Bancária": null,
    "Valor Liberado": null,
    "Data do depósito": null,
    "Modalidade": null,
    "Número/Ano": null,
    "Contrato nº": null,
    "Contratada": null,
    "Vigência do Contrato": null,
    "Assinatura do Contrato": null,
    "Término da Vigência": null,
    "Aditamento de vigência": null,
    "Prazo de Execução": null,
    "Ordem de Início de Serviço": null,
    "Término da Execução": null,
    "Aditamento de Execução": null,
    "Valor do Contrato": null,
    "Ficha Orçamentária RP": null,
    "Nota de Empenho RP": null,
    "RP Vigente": null,
    "Ficha Orçamentária CP": null,
    "Nota de Empenho CP": null,
    "CP Vigente": null,
    "Nota de Empenho Excl": null,
    "Ficha Orçamentária Excl": null,
    "CP Exclusiva/Recurso Próprio": null,
    "Aditamento de Valor": null,
    "CNO": null,
    "% Medição": null,
    "Valor Pago": null,
    "% Pago": null,
    "Saldo de RP": 0,
    "Saldo na conta (rendimentos)": null,
    "Prestação de Contas": null,
    "Processo SPD": null,
    "Processo Crédito Adicional": null,
    "Processo Licitatório": null,
    "Processo Medição": null,
    "Data da Última Medição/Movimentação": null,
    "Dias sem medição": null,
    "Dias sem movimentação": null,
    "Pendências": "Aguardando análise da proposta",
    "Órgão Responsável pela pendência": "MAPA",
    "Engenheiro Responsável": "Adilson",
    "Situação_1": null,
    "Área": "PRODUÇÃO AGRÍCOLA"
  },
  {
    "Data Inicial": 45770,
    "Modalidade do Repasse": "Programa",
    "Proposta/ Demanda": 55875,
    "Termo de  Formalização": null,
    "Número do Termo": null,
    "Data de Assinatura": null,
    "Ano": 2025,
    "Vigência": null,
    "Cláusula Suspensiva": null,
    "Esfera": "Federal",
    "Situação": "Proposta",
    "Parlamentar": null,
    "Partido Político": null,
    "Código da Emenda": null,
    "Função": null,
    "Subfunção": null,
    "Código da Receita": null,
    "Repasse": 31796277.56,
    "Contrapartida": 321174.52,
    "Ministério": null,
    "Programa": "2200020250010 - Fomento ao Setor Agropecuário - Equipamentos, Execução de Custeio, Obras e Serviços de Engenharia",
    "Objeto": "Obras de Pavimentação em Estrada vicinal no Município de Votorantim (Pedro Monari)",
    "Conta Bancária": null,
    "Valor Liberado": null,
    "Data do depósito": null,
    "Modalidade": null,
    "Número/Ano": null,
    "Contrato nº": null,
    "Contratada": null,
    "Vigência do Contrato": null,
    "Assinatura do Contrato": null,
    "Término da Vigência": null,
    "Aditamento de vigência": null,
    "Prazo de Execução": null,
    "Ordem de Início de Serviço": null,
    "Término da Execução": null,
    "Aditamento de Execução": null,
    "Valor do Contrato": null,
    "Ficha Orçamentária RP": null,
    "Nota de Empenho RP": null,
    "RP Vigente": null,
    "Ficha Orçamentária CP": null,
    "Nota de Empenho CP": null,
    "CP Vigente": null,
    "Nota de Empenho Excl": null,
    "Ficha Orçamentária Excl": null,
    "CP Exclusiva/Recurso Próprio": null,
    "Aditamento de Valor": null,
    "CNO": null,
    "% Medição": null,
    "Valor Pago": null,
    "% Pago": null,
    "Saldo de RP": 0,
    "Saldo na conta (rendimentos)": null,
    "Prestação de Contas": null,
    "Processo SPD": null,
    "Processo Crédito Adicional": null,
    "Processo Licitatório": null,
    "Processo Medição": null,
    "Data da Última Medição/Movimentação": null,
    "Dias sem medição": null,
    "Dias sem movimentação": null,
    "Pendências": "Aguardando análise da proposta",
    "Órgão Responsável pela pendência": "MAPA",
    "Engenheiro Responsável": "Adilson",
    "Situação_1": null,
    "Área": "PRODUÇÃO AGRÍCOLA"
  },
  {
    "Data Inicial": 45770,
    "Modalidade do Repasse": "Programa",
    "Proposta/ Demanda": 55846,
    "Termo de  Formalização": null,
    "Número do Termo": null,
    "Data de Assinatura": null,
    "Ano": 2025,
    "Vigência": null,
    "Cláusula Suspensiva": null,
    "Esfera": "Federal",
    "Situação": "Proposta",
    "Parlamentar": null,
    "Partido Político": null,
    "Código da Emenda": null,
    "Função": null,
    "Subfunção": null,
    "Código da Receita": null,
    "Repasse": 24110460,
    "Contrapartida": 243540,
    "Ministério": null,
    "Programa": "5300020250005 - Ação 00SX - Apoio a Projetos de Desenvolvimento Sustentável Local Integrado - RP2 - Equipamentos e Obras",
    "Objeto": "Obras rodoviárias no Município de Votorantim (Interligação Pedro/Jaziel)",
    "Conta Bancária": null,
    "Valor Liberado": null,
    "Data do depósito": null,
    "Modalidade": null,
    "Número/Ano": null,
    "Contrato nº": null,
    "Contratada": null,
    "Vigência do Contrato": null,
    "Assinatura do Contrato": null,
    "Término da Vigência": null,
    "Aditamento de vigência": null,
    "Prazo de Execução": null,
    "Ordem de Início de Serviço": null,
    "Término da Execução": null,
    "Aditamento de Execução": null,
    "Valor do Contrato": null,
    "Ficha Orçamentária RP": null,
    "Nota de Empenho RP": null,
    "RP Vigente": null,
    "Ficha Orçamentária CP": null,
    "Nota de Empenho CP": null,
    "CP Vigente": null,
    "Nota de Empenho Excl": null,
    "Ficha Orçamentária Excl": null,
    "CP Exclusiva/Recurso Próprio": null,
    "Aditamento de Valor": null,
    "CNO": null,
    "% Medição": null,
    "Valor Pago": null,
    "% Pago": null,
    "Saldo de RP": 0,
    "Saldo na conta (rendimentos)": null,
    "Prestação de Contas": null,
    "Processo SPD": null,
    "Processo Crédito Adicional": null,
    "Processo Licitatório": null,
    "Processo Medição": null,
    "Data da Última Medição/Movimentação": null,
    "Dias sem medição": null,
    "Dias sem movimentação": null,
    "Pendências": "Aguardando análise da proposta",
    "Órgão Responsável pela pendência": "MIDR",
    "Engenheiro Responsável": "Adilson",
    "Situação_1": null,
    "Área": "INFRAESTRUTURA PRODUTIVA"
  },
  {
    "Data Inicial": 45791,
    "Modalidade do Repasse": "Programa",
    "Proposta/ Demanda": 55905,
    "Termo de  Formalização": null,
    "Número do Termo": null,
    "Data de Assinatura": null,
    "Ano": 2025,
    "Vigência": null,
    "Cláusula Suspensiva": null,
    "Esfera": "Federal",
    "Situação": "Proposta",
    "Parlamentar": null,
    "Partido Político": null,
    "Código da Emenda": null,
    "Função": null,
    "Subfunção": null,
    "Código da Receita": null,
    "Repasse": 2861100,
    "Contrapartida": 28900,
    "Ministério": null,
    "Programa": "5300020250006 - Ação 00SX - Apoio a Projetos de Desenvolvimento Sustentável Local Integrado - RP2 - Obras",
    "Objeto": "Obras de Pavimentação Vicinal no Município de Votorantim (Capoavinha).",
    "Conta Bancária": null,
    "Valor Liberado": null,
    "Data do depósito": null,
    "Modalidade": null,
    "Número/Ano": null,
    "Contrato nº": null,
    "Contratada": null,
    "Vigência do Contrato": null,
    "Assinatura do Contrato": null,
    "Término da Vigência": null,
    "Aditamento de vigência": null,
    "Prazo de Execução": null,
    "Ordem de Início de Serviço": null,
    "Término da Execução": null,
    "Aditamento de Execução": null,
    "Valor do Contrato": null,
    "Ficha Orçamentária RP": null,
    "Nota de Empenho RP": null,
    "RP Vigente": null,
    "Ficha Orçamentária CP": null,
    "Nota de Empenho CP": null,
    "CP Vigente": null,
    "Nota de Empenho Excl": null,
    "Ficha Orçamentária Excl": null,
    "CP Exclusiva/Recurso Próprio": null,
    "Aditamento de Valor": null,
    "CNO": null,
    "% Medição": null,
    "Valor Pago": null,
    "% Pago": null,
    "Saldo de RP": 0,
    "Saldo na conta (rendimentos)": null,
    "Prestação de Contas": null,
    "Processo SPD": null,
    "Processo Crédito Adicional": null,
    "Processo Licitatório": null,
    "Processo Medição": null,
    "Data da Última Medição/Movimentação": null,
    "Dias sem medição": null,
    "Dias sem movimentação": null,
    "Pendências": "Aguardando análise da proposta",
    "Órgão Responsável pela pendência": "MIDR",
    "Engenheiro Responsável": "Adilson",
    "Situação_1": null,
    "Área": "INFRAESTRUTURA PRODUTIVA"
  },
  {
    "Data Inicial": 45791,
    "Modalidade do Repasse": "Programa",
    "Proposta/ Demanda": null,
    "Termo de  Formalização": null,
    "Número do Termo": null,
    "Data de Assinatura": null,
    "Ano": 2025,
    "Vigência": null,
    "Cláusula Suspensiva": null,
    "Esfera": "Federal",
    "Situação": "Proposta",
    "Parlamentar": null,
    "Partido Político": null,
    "Código da Emenda": null,
    "Função": null,
    "Subfunção": null,
    "Código da Receita": null,
    "Repasse": null,
    "Contrapartida": null,
    "Ministério": null,
    "Programa": "6900020250015 - Evolução das Microempresas e das Empresas de Pequeno Porte visando a interiorização das estratégias para a implementação da Política Nacional de Desenvolvimento das Microempresas e Empresas de Pequeno Porte",
    "Objeto": "Feira Empreendedora",
    "Conta Bancária": null,
    "Valor Liberado": null,
    "Data do depósito": null,
    "Modalidade": null,
    "Número/Ano": null,
    "Contrato nº": null,
    "Contratada": null,
    "Vigência do Contrato": null,
    "Assinatura do Contrato": null,
    "Término da Vigência": null,
    "Aditamento de vigência": null,
    "Prazo de Execução": null,
    "Ordem de Início de Serviço": null,
    "Término da Execução": null,
    "Aditamento de Execução": null,
    "Valor do Contrato": null,
    "Ficha Orçamentária RP": null,
    "Nota de Empenho RP": null,
    "RP Vigente": null,
    "Ficha Orçamentária CP": null,
    "Nota de Empenho CP": null,
    "CP Vigente": null,
    "Nota de Empenho Excl": null,
    "Ficha Orçamentária Excl": null,
    "CP Exclusiva/Recurso Próprio": null,
    "Aditamento de Valor": null,
    "CNO": null,
    "% Medição": null,
    "Valor Pago": null,
    "% Pago": null,
    "Saldo de RP": 0,
    "Saldo na conta (rendimentos)": null,
    "Prestação de Contas": null,
    "Processo SPD": null,
    "Processo Crédito Adicional": null,
    "Processo Licitatório": null,
    "Processo Medição": null,
    "Data da Última Medição/Movimentação": null,
    "Dias sem medição": null,
    "Dias sem movimentação": null,
    "Pendências": "Aguardando aprovação do Plano de Trabalho",
    "Órgão Responsável pela pendência": "Carlota",
    "Engenheiro Responsável": null,
    "Situação_1": null,
    "Área": "MEs e EPPs"
  },
  {
    "Data Inicial": 45764,
    "Modalidade do Repasse": "Programa",
    "Proposta/ Demanda": null,
    "Termo de  Formalização": null,
    "Número do Termo": null,
    "Data de Assinatura": null,
    "Ano": 2025,
    "Vigência": null,
    "Cláusula Suspensiva": null,
    "Esfera": "Federal",
    "Situação": "Proposta",
    "Parlamentar": null,
    "Partido Político": null,
    "Código da Emenda": null,
    "Função": null,
    "Subfunção": null,
    "Código da Receita": null,
    "Repasse": 3580655.2,
    "Contrapartida": null,
    "Ministério": null,
    "Programa": "Política Nacional Aldir Blanc de Fomento à Cultura",
    "Objeto": "Custeio",
    "Conta Bancária": null,
    "Valor Liberado": null,
    "Data do depósito": null,
    "Modalidade": null,
    "Número/Ano": null,
    "Contrato nº": null,
    "Contratada": null,
    "Vigência do Contrato": null,
    "Assinatura do Contrato": null,
    "Término da Vigência": null,
    "Aditamento de vigência": null,
    "Prazo de Execução": null,
    "Ordem de Início de Serviço": null,
    "Término da Execução": null,
    "Aditamento de Execução": null,
    "Valor do Contrato": null,
    "Ficha Orçamentária RP": null,
    "Nota de Empenho RP": null,
    "RP Vigente": null,
    "Ficha Orçamentária CP": null,
    "Nota de Empenho CP": null,
    "CP Vigente": null,
    "Nota de Empenho Excl": null,
    "Ficha Orçamentária Excl": null,
    "CP Exclusiva/Recurso Próprio": null,
    "Aditamento de Valor": null,
    "CNO": null,
    "% Medição": null,
    "Valor Pago": null,
    "% Pago": null,
    "Saldo de RP": 0,
    "Saldo na conta (rendimentos)": null,
    "Prestação de Contas": null,
    "Processo SPD": null,
    "Processo Crédito Adicional": null,
    "Processo Licitatório": null,
    "Processo Medição": null,
    "Data da Última Medição/Movimentação": null,
    "Dias sem medição": null,
    "Dias sem movimentação": null,
    "Pendências": "Plano de Ação Aprovado",
    "Órgão Responsável pela pendência": "SECULT",
    "Engenheiro Responsável": null,
    "Situação_1": null,
    "Área": "CULTURA"
  },
  {
    "Data Inicial": 45862,
    "Modalidade do Repasse": "Transferência Voluntária",
    "Proposta/ Demanda": 95209,
    "Termo de  Formalização": "Convênio",
    "Número do Termo": "100286/2025",
    "Data de Assinatura": 45975,
    "Ano": 2025,
    "Vigência": 46705,
    "Cláusula Suspensiva": null,
    "Esfera": "Estadual",
    "Situação": "Assinado",
    "Parlamentar": null,
    "Partido Político": null,
    "Código da Emenda": null,
    "Função": null,
    "Subfunção": null,
    "Código da Receita": null,
    "Repasse": 5000000,
    "Contrapartida": 246220.9,
    "Ministério": null,
    "Programa": "674 - Infraestrutura Urbana",
    "Objeto": "Pavimentação asfáltica da Estrada do Moranguinho, Estrada do Cubatão e Rua Espedito ",
    "Conta Bancária": "46.471-6",
    "Valor Liberado": null,
    "Data do depósito": null,
    "Modalidade": null,
    "Número/Ano": null,
    "Contrato nº": null,
    "Contratada": null,
    "Vigência do Contrato": null,
    "Assinatura do Contrato": null,
    "Término da Vigência": null,
    "Aditamento de vigência": null,
    "Prazo de Execução": null,
    "Ordem de Início de Serviço": null,
    "Término da Execução": null,
    "Aditamento de Execução": null,
    "Valor do Contrato": null,
    "Ficha Orçamentária RP": null,
    "Nota de Empenho RP": null,
    "RP Vigente": null,
    "Ficha Orçamentária CP": null,
    "Nota de Empenho CP": null,
    "CP Vigente": null,
    "Nota de Empenho Excl": null,
    "Ficha Orçamentária Excl": null,
    "CP Exclusiva/Recurso Próprio": null,
    "Aditamento de Valor": null,
    "CNO": null,
    "% Medição": null,
    "Valor Pago": null,
    "% Pago": null,
    "Saldo de RP": 0,
    "Saldo na conta (rendimentos)": null,
    "Prestação de Contas": null,
    "Processo SPD": "1331/2025",
    "Processo Crédito Adicional": "C.I 236_2025",
    "Processo Licitatório": null,
    "Processo Medição": null,
    "Data da Última Medição/Movimentação": null,
    "Dias sem medição": null,
    "Dias sem movimentação": null,
    "Pendências": "1. Aguardando a emissão da Nota de Empenho\n2. Aguardando processo licitatório\n3. Implantação de rede de esgoto\n4. Implantação de postes de IP na descida",
    "Órgão Responsável pela pendência": "1. SGRI\n2. SOURB\n3. CAV\n4. PMV",
    "Engenheiro Responsável": "Adilson",
    "Situação_1": null,
    "Área": "INFRAESTRUTURA"
  },
  {
    "Data Inicial": 45888,
    "Modalidade do Repasse": "Programa",
    "Proposta/ Demanda": 95708,
    "Termo de  Formalização": null,
    "Número do Termo": null,
    "Data de Assinatura": null,
    "Ano": 2025,
    "Vigência": null,
    "Cláusula Suspensiva": null,
    "Esfera": "Estadual",
    "Situação": "Proposta",
    "Parlamentar": null,
    "Partido Político": null,
    "Código da Emenda": null,
    "Função": null,
    "Subfunção": null,
    "Código da Receita": null,
    "Repasse": 194500,
    "Contrapartida": null,
    "Ministério": null,
    "Programa": "(PAINSP) ALFABETIZA JUNTOS SP - Prêmio Excelência Educacional",
    "Objeto": "Prêmio Excelência Educacional",
    "Conta Bancária": null,
    "Valor Liberado": null,
    "Data do depósito": null,
    "Modalidade": null,
    "Número/Ano": null,
    "Contrato nº": null,
    "Contratada": null,
    "Vigência do Contrato": null,
    "Assinatura do Contrato": null,
    "Término da Vigência": null,
    "Aditamento de vigência": null,
    "Prazo de Execução": null,
    "Ordem de Início de Serviço": null,
    "Término da Execução": null,
    "Aditamento de Execução": null,
    "Valor do Contrato": null,
    "Ficha Orçamentária RP": null,
    "Nota de Empenho RP": null,
    "RP Vigente": null,
    "Ficha Orçamentária CP": null,
    "Nota de Empenho CP": null,
    "CP Vigente": null,
    "Nota de Empenho Excl": null,
    "Ficha Orçamentária Excl": null,
    "CP Exclusiva/Recurso Próprio": null,
    "Aditamento de Valor": null,
    "CNO": null,
    "% Medição": null,
    "Valor Pago": null,
    "% Pago": null,
    "Saldo de RP": null,
    "Saldo na conta (rendimentos)": null,
    "Prestação de Contas": null,
    "Processo SPD": null,
    "Processo Crédito Adicional": null,
    "Processo Licitatório": null,
    "Processo Medição": null,
    "Data da Última Medição/Movimentação": null,
    "Dias sem medição": null,
    "Dias sem movimentação": null,
    "Pendências": "Em execução do pagamento - COEFIN/DIORF",
    "Órgão Responsável pela pendência": "SEED",
    "Engenheiro Responsável": null,
    "Situação_1": null,
    "Área": "EDUCAÇÃO"
  },
  {
    "Data Inicial": 45897,
    "Modalidade do Repasse": "Programa",
    "Proposta/ Demanda": null,
    "Termo de  Formalização": null,
    "Número do Termo": null,
    "Data de Assinatura": null,
    "Ano": 2025,
    "Vigência": null,
    "Cláusula Suspensiva": null,
    "Esfera": "Estadual",
    "Situação": "Proposta",
    "Parlamentar": null,
    "Partido Político": null,
    "Código da Emenda": null,
    "Função": null,
    "Subfunção": null,
    "Código da Receita": null,
    "Repasse": null,
    "Contrapartida": null,
    "Ministério": null,
    "Programa": "FECOP",
    "Objeto": "Aquisição de prancha (FECOP)",
    "Conta Bancária": null,
    "Valor Liberado": null,
    "Data do depósito": null,
    "Modalidade": null,
    "Número/Ano": null,
    "Contrato nº": null,
    "Contratada": null,
    "Vigência do Contrato": null,
    "Assinatura do Contrato": null,
    "Término da Vigência": null,
    "Aditamento de vigência": null,
    "Prazo de Execução": null,
    "Ordem de Início de Serviço": null,
    "Término da Execução": null,
    "Aditamento de Execução": null,
    "Valor do Contrato": null,
    "Ficha Orçamentária RP": null,
    "Nota de Empenho RP": null,
    "RP Vigente": null,
    "Ficha Orçamentária CP": null,
    "Nota de Empenho CP": null,
    "CP Vigente": null,
    "Nota de Empenho Excl": null,
    "Ficha Orçamentária Excl": null,
    "CP Exclusiva/Recurso Próprio": null,
    "Aditamento de Valor": null,
    "CNO": null,
    "% Medição": null,
    "Valor Pago": null,
    "% Pago": null,
    "Saldo de RP": null,
    "Saldo na conta (rendimentos)": null,
    "Prestação de Contas": null,
    "Processo SPD": "1299/2025",
    "Processo Crédito Adicional": null,
    "Processo Licitatório": null,
    "Processo Medição": null,
    "Data da Última Medição/Movimentação": null,
    "Dias sem medição": null,
    "Dias sem movimentação": null,
    "Pendências": "Edital Publicado - CHAMADA PÚBLICA Nº 01/2025",
    "Órgão Responsável pela pendência": "SEMIL",
    "Engenheiro Responsável": null,
    "Situação_1": null,
    "Área": "RESÍDUOS SÓLIDOS"
  },
  {
    "Data Inicial": 45925,
    "Modalidade do Repasse": "Transferência Voluntária",
    "Proposta/ Demanda": 98053,
    "Termo de  Formalização": null,
    "Número do Termo": null,
    "Data de Assinatura": null,
    "Ano": 2025,
    "Vigência": null,
    "Cláusula Suspensiva": null,
    "Esfera": "Estadual",
    "Situação": "Proposta",
    "Parlamentar": "Rogério Santos",
    "Partido Político": null,
    "Código da Emenda": "2025.263.75794",
    "Função": null,
    "Subfunção": null,
    "Código da Receita": null,
    "Repasse": 370000,
    "Contrapartida": null,
    "Ministério": null,
    "Programa": "Obras Esportivas",
    "Objeto": "Construção de Campo de Futebol",
    "Conta Bancária": null,
    "Valor Liberado": null,
    "Data do depósito": null,
    "Modalidade": null,
    "Número/Ano": null,
    "Contrato nº": null,
    "Contratada": null,
    "Vigência do Contrato": null,
    "Assinatura do Contrato": null,
    "Término da Vigência": null,
    "Aditamento de vigência": null,
    "Prazo de Execução": null,
    "Ordem de Início de Serviço": null,
    "Término da Execução": null,
    "Aditamento de Execução": null,
    "Valor do Contrato": null,
    "Ficha Orçamentária RP": null,
    "Nota de Empenho RP": null,
    "RP Vigente": null,
    "Ficha Orçamentária CP": null,
    "Nota de Empenho CP": null,
    "CP Vigente": null,
    "Nota de Empenho Excl": null,
    "Ficha Orçamentária Excl": null,
    "CP Exclusiva/Recurso Próprio": null,
    "Aditamento de Valor": null,
    "CNO": null,
    "% Medição": null,
    "Valor Pago": null,
    "% Pago": null,
    "Saldo de RP": null,
    "Saldo na conta (rendimentos)": null,
    "Prestação de Contas": null,
    "Processo SPD": null,
    "Processo Crédito Adicional": null,
    "Processo Licitatório": null,
    "Processo Medição": null,
    "Data da Última Medição/Movimentação": null,
    "Dias sem medição": null,
    "Dias sem movimentação": null,
    "Pendências": "Aguardando matrícula da área",
    "Órgão Responsável pela pendência": "SENJ",
    "Engenheiro Responsável": null,
    "Situação_1": null,
    "Área": "ESPORTE"
  },
  {
    "Data Inicial": null,
    "Modalidade do Repasse": null,
    "Proposta/ Demanda": 97945,
    "Termo de  Formalização": null,
    "Número do Termo": null,
    "Data de Assinatura": null,
    "Ano": 2025,
    "Vigência": null,
    "Cláusula Suspensiva": null,
    "Esfera": "Estadual",
    "Situação": "Proposta",
    "Parlamentar": null,
    "Partido Político": null,
    "Código da Emenda": null,
    "Função": null,
    "Subfunção": null,
    "Código da Receita": null,
    "Repasse": null,
    "Contrapartida": null,
    "Ministério": null,
    "Programa": " (PAINSP) ALFABETIZA JUNTOS SP - Plataformas Digitais - Alfabetização",
    "Objeto": "Plataformas Digitais - Alfabetização",
    "Conta Bancária": null,
    "Valor Liberado": null,
    "Data do depósito": null,
    "Modalidade": null,
    "Número/Ano": null,
    "Contrato nº": null,
    "Contratada": null,
    "Vigência do Contrato": null,
    "Assinatura do Contrato": null,
    "Término da Vigência": null,
    "Aditamento de vigência": null,
    "Prazo de Execução": null,
    "Ordem de Início de Serviço": null,
    "Término da Execução": null,
    "Aditamento de Execução": null,
    "Valor do Contrato": null,
    "Ficha Orçamentária RP": null,
    "Nota de Empenho RP": null,
    "RP Vigente": null,
    "Ficha Orçamentária CP": null,
    "Nota de Empenho CP": null,
    "CP Vigente": null,
    "Nota de Empenho Excl": null,
    "Ficha Orçamentária Excl": null,
    "CP Exclusiva/Recurso Próprio": null,
    "Aditamento de Valor": null,
    "CNO": null,
    "% Medição": null,
    "Valor Pago": null,
    "% Pago": null,
    "Saldo de RP": null,
    "Saldo na conta (rendimentos)": null,
    "Prestação de Contas": null,
    "Processo SPD": null,
    "Processo Crédito Adicional": null,
    "Processo Licitatório": null,
    "Processo Medição": null,
    "Data da Última Medição/Movimentação": null,
    "Dias sem medição": null,
    "Dias sem movimentação": null,
    "Pendências": "Aguardando Assinaturas",
    "Órgão Responsável pela pendência": null,
    "Engenheiro Responsável": null,
    "Situação_1": null,
    "Área": null
  },
  {
    "Data Inicial": 45940,
    "Modalidade do Repasse": "Transferência Voluntária",
    "Proposta/ Demanda": null,
    "Termo de  Formalização": null,
    "Número do Termo": null,
    "Data de Assinatura": null,
    "Ano": 2025,
    "Vigência": null,
    "Cláusula Suspensiva": null,
    "Esfera": "Estadual",
    "Situação": "Indicação",
    "Parlamentar": "Vitão do Cachorrão",
    "Partido Político": null,
    "Código da Emenda": "2025.289.76524",
    "Função": null,
    "Subfunção": null,
    "Código da Receita": null,
    "Repasse": 500000,
    "Contrapartida": null,
    "Ministério": null,
    "Programa": null,
    "Objeto": "Construção de um campo de futebol society, no bairro São Lucas",
    "Conta Bancária": null,
    "Valor Liberado": null,
    "Data do depósito": null,
    "Modalidade": null,
    "Número/Ano": null,
    "Contrato nº": null,
    "Contratada": null,
    "Vigência do Contrato": null,
    "Assinatura do Contrato": null,
    "Término da Vigência": null,
    "Aditamento de vigência": null,
    "Prazo de Execução": null,
    "Ordem de Início de Serviço": null,
    "Término da Execução": null,
    "Aditamento de Execução": null,
    "Valor do Contrato": null,
    "Ficha Orçamentária RP": null,
    "Nota de Empenho RP": null,
    "RP Vigente": null,
    "Ficha Orçamentária CP": null,
    "Nota de Empenho CP": null,
    "CP Vigente": null,
    "Nota de Empenho Excl": null,
    "Ficha Orçamentária Excl": null,
    "CP Exclusiva/Recurso Próprio": null,
    "Aditamento de Valor": null,
    "CNO": null,
    "% Medição": null,
    "Valor Pago": null,
    "% Pago": null,
    "Saldo de RP": null,
    "Saldo na conta (rendimentos)": null,
    "Prestação de Contas": null,
    "Processo SPD": "1735/2025",
    "Processo Crédito Adicional": null,
    "Processo Licitatório": null,
    "Processo Medição": null,
    "Data da Última Medição/Movimentação": null,
    "Dias sem medição": null,
    "Dias sem movimentação": null,
    "Pendências": "1. Aguardando definição do objeto\n2. Posteriormente, solicitar ao deputado a alteração do objeto",
    "Órgão Responsável pela pendência": "1. SOURB\n2 SEDESP",
    "Engenheiro Responsável": null,
    "Situação_1": null,
    "Área": null
  },
  {
    "Data Inicial": 45951,
    "Modalidade do Repasse": "Transferência Especial",
    "Proposta/ Demanda": "025.00012742/2025-39",
    "Termo de  Formalização": "Plano de Trabalho",
    "Número do Termo": null,
    "Data de Assinatura": 45951,
    "Ano": 2025,
    "Vigência": 46681,
    "Cláusula Suspensiva": null,
    "Esfera": "Estadual",
    "Situação": "Assinado",
    "Parlamentar": "Adilson Barroso",
    "Partido Político": null,
    "Código da Emenda": "2025.429.20005",
    "Função": null,
    "Subfunção": null,
    "Código da Receita": null,
    "Repasse": 253255.81,
    "Contrapartida": null,
    "Ministério": null,
    "Programa": "Todos contra a Desordem",
    "Objeto": "Aquisição de 01 (uma) viatura caracterizada - veículo automotor, tipo camioneta, utilitário (SUV - Sport Utility Vehicle) médio porte ou Minivan, montado em estrutura monobloco, equipado com sistema de tração 4x2 ou sistema de tração integral, carroceria em aço e original de fábrica, zero-quilômetro de fábrica, destinado ao transporte de passageiros e carga no mesmo compartimento, em cor sólida, modificado para policiamento ostensivo, com o objetivo de apoiar as atividades institucionais da GCM da localidade",
    "Conta Bancária": null,
    "Valor Liberado": null,
    "Data do depósito": null,
    "Modalidade": null,
    "Número/Ano": null,
    "Contrato nº": null,
    "Contratada": null,
    "Vigência do Contrato": null,
    "Assinatura do Contrato": null,
    "Término da Vigência": null,
    "Aditamento de vigência": null,
    "Prazo de Execução": null,
    "Ordem de Início de Serviço": null,
    "Término da Execução": null,
    "Aditamento de Execução": null,
    "Valor do Contrato": null,
    "Ficha Orçamentária RP": null,
    "Nota de Empenho RP": null,
    "RP Vigente": null,
    "Ficha Orçamentária CP": null,
    "Nota de Empenho CP": null,
    "CP Vigente": null,
    "Nota de Empenho Excl": null,
    "Ficha Orçamentária Excl": null,
    "CP Exclusiva/Recurso Próprio": null,
    "Aditamento de Valor": null,
    "CNO": null,
    "% Medição": null,
    "Valor Pago": null,
    "% Pago": null,
    "Saldo de RP": null,
    "Saldo na conta (rendimentos)": null,
    "Prestação de Contas": null,
    "Processo SPD": null,
    "Processo Crédito Adicional": null,
    "Processo Licitatório": null,
    "Processo Medição": null,
    "Data da Última Medição/Movimentação": null,
    "Dias sem medição": null,
    "Dias sem movimentação": null,
    "Pendências": "1. Aguardando liberação do repasse\n2. Aguardando abertura de conta bancária",
    "Órgão Responsável pela pendência": "1. SSP\n2. SPD",
    "Engenheiro Responsável": null,
    "Situação_1": null,
    "Área": null
  },
  {
    "Data Inicial": 45978,
    "Modalidade do Repasse": "Transferência Voluntária",
    "Proposta/ Demanda": 99099,
    "Termo de  Formalização": null,
    "Número do Termo": null,
    "Data de Assinatura": null,
    "Ano": 2025,
    "Vigência": null,
    "Cláusula Suspensiva": null,
    "Esfera": "Estadual",
    "Situação": "Proposta",
    "Parlamentar": "Agente Federal Danilo Balas",
    "Partido Político": null,
    "Código da Emenda": "2025.005.77350",
    "Função": "06 - Segurança Pública",
    "Subfunção": "181 - Policiamento",
    "Código da Receita": null,
    "Repasse": 150000,
    "Contrapartida": 18900.67,
    "Ministério": null,
    "Programa": "462 - Aquisição de equipamentos da SSP",
    "Objeto": "Aquisição de equipamento e serviços de Tecnologia da informação e Comunicação ",
    "Conta Bancária": "47669-2",
    "Valor Liberado": null,
    "Data do depósito": null,
    "Modalidade": null,
    "Número/Ano": null,
    "Contrato nº": null,
    "Contratada": null,
    "Vigência do Contrato": null,
    "Assinatura do Contrato": null,
    "Término da Vigência": null,
    "Aditamento de vigência": null,
    "Prazo de Execução": null,
    "Ordem de Início de Serviço": null,
    "Término da Execução": null,
    "Aditamento de Execução": null,
    "Valor do Contrato": null,
    "Ficha Orçamentária RP": null,
    "Nota de Empenho RP": null,
    "RP Vigente": null,
    "Ficha Orçamentária CP": null,
    "Nota de Empenho CP": null,
    "CP Vigente": null,
    "Nota de Empenho Excl": null,
    "Ficha Orçamentária Excl": null,
    "CP Exclusiva/Recurso Próprio": null,
    "Aditamento de Valor": null,
    "CNO": null,
    "% Medição": null,
    "Valor Pago": null,
    "% Pago": null,
    "Saldo de RP": null,
    "Saldo na conta (rendimentos)": null,
    "Prestação de Contas": null,
    "Processo SPD": null,
    "Processo Crédito Adicional": null,
    "Processo Licitatório": null,
    "Processo Medição": null,
    "Data da Última Medição/Movimentação": null,
    "Dias sem medição": null,
    "Dias sem movimentação": null,
    "Pendências": "Aguardando análise técnica",
    "Órgão Responsável pela pendência": "SSP",
    "Engenheiro Responsável": null,
    "Situação_1": null,
    "Área": "SEGURANÇA"
  },
  {
    "Data Inicial": " 02/12/2025",
    "Modalidade do Repasse": "Transferência Voluntária",
    "Proposta/ Demanda": 99447,
    "Termo de  Formalização": null,
    "Número do Termo": null,
    "Data de Assinatura": null,
    "Ano": 2025,
    "Vigência": null,
    "Cláusula Suspensiva": null,
    "Esfera": "Estadual",
    "Situação": "Proposta",
    "Parlamentar": "Maria Lúcia Amary",
    "Partido Político": null,
    "Código da Emenda": "2025.065.77512",
    "Função": "15 - Urbanismo",
    "Subfunção": "451 - Infraestrutura Urbana ",
    "Código da Receita": null,
    "Repasse": 150000,
    "Contrapartida": null,
    "Ministério": null,
    "Programa": "674 - Infraestrutura Urbana",
    "Objeto": "Recapeamento das Francisco de Paula e Noé Carlos de Campos",
    "Conta Bancária": "47670-6",
    "Valor Liberado": null,
    "Data do depósito": null,
    "Modalidade": null,
    "Número/Ano": null,
    "Contrato nº": null,
    "Contratada": null,
    "Vigência do Contrato": null,
    "Assinatura do Contrato": null,
    "Término da Vigência": null,
    "Aditamento de vigência": null,
    "Prazo de Execução": null,
    "Ordem de Início de Serviço": null,
    "Término da Execução": null,
    "Aditamento de Execução": null,
    "Valor do Contrato": null,
    "Ficha Orçamentária RP": null,
    "Nota de Empenho RP": null,
    "RP Vigente": null,
    "Ficha Orçamentária CP": null,
    "Nota de Empenho CP": null,
    "CP Vigente": null,
    "Nota de Empenho Excl": null,
    "Ficha Orçamentária Excl": null,
    "CP Exclusiva/Recurso Próprio": null,
    "Aditamento de Valor": null,
    "CNO": null,
    "% Medição": null,
    "Valor Pago": null,
    "% Pago": null,
    "Saldo de RP": null,
    "Saldo na conta (rendimentos)": null,
    "Prestação de Contas": null,
    "Processo SPD": null,
    "Processo Crédito Adicional": null,
    "Processo Licitatório": null,
    "Processo Medição": null,
    "Data da Última Medição/Movimentação": null,
    "Dias sem medição": null,
    "Dias sem movimentação": null,
    "Pendências": "1. Aguardando projeto\n2 Aguardando abertura de conta bancária",
    "Órgão Responsável pela pendência": "1. SOURB\n2. SEF",
    "Engenheiro Responsável": null,
    "Situação_1": null,
    "Área": "INFRAESTRUTURA"
  },
  {
    "Data Inicial": 45995,
    "Modalidade do Repasse": "Doação",
    "Proposta/ Demanda": null,
    "Termo de  Formalização": null,
    "Número do Termo": null,
    "Data de Assinatura": null,
    "Ano": 2025,
    "Vigência": null,
    "Cláusula Suspensiva": null,
    "Esfera": "Federal",
    "Situação": "Proposta",
    "Parlamentar": "Eduardo Bolsonaro",
    "Partido Político": null,
    "Código da Emenda": 30880008,
    "Função": "06 - Segurança Pública",
    "Subfunção": "181 - Policiamento",
    "Código da Receita": null,
    "Repasse": 400000,
    "Contrapartida": null,
    "Ministério": null,
    "Programa": null,
    "Objeto": "Aquisição Direta (Doação)",
    "Conta Bancária": null,
    "Valor Liberado": null,
    "Data do depósito": null,
    "Modalidade": null,
    "Número/Ano": null,
    "Contrato nº": null,
    "Contratada": null,
    "Vigência do Contrato": null,
    "Assinatura do Contrato": null,
    "Término da Vigência": null,
    "Aditamento de vigência": null,
    "Prazo de Execução": null,
    "Ordem de Início de Serviço": null,
    "Término da Execução": null,
    "Aditamento de Execução": null,
    "Valor do Contrato": null,
    "Ficha Orçamentária RP": null,
    "Nota de Empenho RP": null,
    "RP Vigente": null,
    "Ficha Orçamentária CP": null,
    "Nota de Empenho CP": null,
    "CP Vigente": null,
    "Nota de Empenho Excl": null,
    "Ficha Orçamentária Excl": null,
    "CP Exclusiva/Recurso Próprio": null,
    "Aditamento de Valor": null,
    "CNO": null,
    "% Medição": null,
    "Valor Pago": null,
    "% Pago": null,
    "Saldo de RP": null,
    "Saldo na conta (rendimentos)": null,
    "Prestação de Contas": null,
    "Processo SPD": null,
    "Processo Crédito Adicional": null,
    "Processo Licitatório": null,
    "Processo Medição": null,
    "Data da Última Medição/Movimentação": null,
    "Dias sem medição": null,
    "Dias sem movimentação": null,
    "Pendências": "Aguardando formalização da doação",
    "Órgão Responsável pela pendência": "MJSP",
    "Engenheiro Responsável": null,
    "Situação_1": null,
    "Área": null
  },
  {
    "Data Inicial": 46009,
    "Modalidade do Repasse": "Transferência Voluntária",
    "Proposta/ Demanda": 68229,
    "Termo de  Formalização": null,
    "Número do Termo": null,
    "Data de Assinatura": null,
    "Ano": 2025,
    "Vigência": null,
    "Cláusula Suspensiva": null,
    "Esfera": "Federal",
    "Situação": "Proposta",
    "Parlamentar": null,
    "Partido Político": null,
    "Código da Emenda": null,
    "Função": null,
    "Subfunção": null,
    "Código da Receita": null,
    "Repasse": 2500000,
    "Contrapartida": 25252.53,
    "Ministério": "MCIDADES",
    "Programa": "SNDUM - MCidades 00SY - Apoio a Projetos e Obras de Reabilitação, de Acessibilidade e Modernização Tecnológica em Áreas Urbanas - RP2",
    "Objeto": "Revitalização de Espaços Públicos do Município de Votorantim/SP.",
    "Conta Bancária": null,
    "Valor Liberado": null,
    "Data do depósito": null,
    "Modalidade": null,
    "Número/Ano": null,
    "Contrato nº": null,
    "Contratada": null,
    "Vigência do Contrato": null,
    "Assinatura do Contrato": null,
    "Término da Vigência": null,
    "Aditamento de vigência": null,
    "Prazo de Execução": null,
    "Ordem de Início de Serviço": null,
    "Término da Execução": null,
    "Aditamento de Execução": null,
    "Valor do Contrato": null,
    "Ficha Orçamentária RP": null,
    "Nota de Empenho RP": null,
    "RP Vigente": null,
    "Ficha Orçamentária CP": null,
    "Nota de Empenho CP": null,
    "CP Vigente": null,
    "Nota de Empenho Excl": null,
    "Ficha Orçamentária Excl": null,
    "CP Exclusiva/Recurso Próprio": null,
    "Aditamento de Valor": null,
    "CNO": null,
    "% Medição": null,
    "Valor Pago": null,
    "% Pago": null,
    "Saldo de RP": null,
    "Saldo na conta (rendimentos)": null,
    "Prestação de Contas": null,
    "Processo SPD": null,
    "Processo Crédito Adicional": null,
    "Processo Licitatório": null,
    "Processo Medição": null,
    "Data da Última Medição/Movimentação": null,
    "Dias sem medição": null,
    "Dias sem movimentação": null,
    "Pendências": "Proposta Aprovada. \nAguardando análise do Plano de Trabalho",
    "Órgão Responsável pela pendência": "MCIDADES",
    "Engenheiro Responsável": null,
    "Situação_1": null,
    "Área": null
  },
  {
    "Data Inicial": 46009,
    "Modalidade do Repasse": "Transferência Voluntária",
    "Proposta/ Demanda": 68238,
    "Termo de  Formalização": null,
    "Número do Termo": null,
    "Data de Assinatura": null,
    "Ano": 2025,
    "Vigência": null,
    "Cláusula Suspensiva": null,
    "Esfera": "Federal",
    "Situação": "Proposta",
    "Parlamentar": null,
    "Partido Político": null,
    "Código da Emenda": null,
    "Função": null,
    "Subfunção": null,
    "Código da Receita": null,
    "Repasse": 1485000,
    "Contrapartida": 15000,
    "Ministério": "MCIDADES",
    "Programa": "Programa 2319 - Ação 00T1 - Apoio a Politica Nacional de Desenvolvimento Urbano Voltado a Implantação e Qualificação Viaria – RP2",
    "Objeto": "Implantação de qualificação de vias urbanas no Município de Votorantim/SP.",
    "Conta Bancária": null,
    "Valor Liberado": null,
    "Data do depósito": null,
    "Modalidade": null,
    "Número/Ano": null,
    "Contrato nº": null,
    "Contratada": null,
    "Vigência do Contrato": null,
    "Assinatura do Contrato": null,
    "Término da Vigência": null,
    "Aditamento de vigência": null,
    "Prazo de Execução": null,
    "Ordem de Início de Serviço": null,
    "Término da Execução": null,
    "Aditamento de Execução": null,
    "Valor do Contrato": null,
    "Ficha Orçamentária RP": null,
    "Nota de Empenho RP": null,
    "RP Vigente": null,
    "Ficha Orçamentária CP": null,
    "Nota de Empenho CP": null,
    "CP Vigente": null,
    "Nota de Empenho Excl": null,
    "Ficha Orçamentária Excl": null,
    "CP Exclusiva/Recurso Próprio": null,
    "Aditamento de Valor": null,
    "CNO": null,
    "% Medição": null,
    "Valor Pago": null,
    "% Pago": null,
    "Saldo de RP": null,
    "Saldo na conta (rendimentos)": null,
    "Prestação de Contas": null,
    "Processo SPD": null,
    "Processo Crédito Adicional": null,
    "Processo Licitatório": null,
    "Processo Medição": null,
    "Data da Última Medição/Movimentação": null,
    "Dias sem medição": null,
    "Dias sem movimentação": null,
    "Pendências": "Aguardando análise da proposta",
    "Órgão Responsável pela pendência": "MCIDADES",
    "Engenheiro Responsável": null,
    "Situação_1": null,
    "Área": null
  },
  {
    "Data Inicial": null,
    "Modalidade do Repasse": null,
    "Proposta/ Demanda": null,
    "Termo de  Formalização": null,
    "Número do Termo": null,
    "Data de Assinatura": null,
    "Ano": null,
    "Vigência": null,
    "Cláusula Suspensiva": null,
    "Esfera": null,
    "Situação": null,
    "Parlamentar": null,
    "Partido Político": null,
    "Código da Emenda": 202181000740,
    "Função": "Zancheta",
    "Subfunção": null,
    "Código da Receita": null,
    "Repasse": null,
    "Contrapartida": null,
    "Ministério": null,
    "Programa": null,
    "Objeto": null,
    "Conta Bancária": null,
    "Valor Liberado": null,
    "Data do depósito": null,
    "Modalidade": null,
    "Número/Ano": null,
    "Contrato nº": null,
    "Contratada": null,
    "Vigência do Contrato": null,
    "Assinatura do Contrato": null,
    "Término da Vigência": null,
    "Aditamento de vigência": null,
    "Prazo de Execução": null,
    "Ordem de Início de Serviço": null,
    "Término da Execução": null,
    "Aditamento de Execução": null,
    "Valor do Contrato": null,
    "Ficha Orçamentária RP": null,
    "Nota de Empenho RP": null,
    "RP Vigente": null,
    "Ficha Orçamentária CP": null,
    "Nota de Empenho CP": null,
    "CP Vigente": null,
    "Nota de Empenho Excl": null,
    "Ficha Orçamentária Excl": null,
    "CP Exclusiva/Recurso Próprio": null,
    "Aditamento de Valor": null,
    "CNO": null,
    "% Medição": null,
    "Valor Pago": null,
    "% Pago": null,
    "Saldo de RP": null,
    "Saldo na conta (rendimentos)": null,
    "Prestação de Contas": null,
    "Processo SPD": null,
    "Processo Crédito Adicional": null,
    "Processo Licitatório": null,
    "Processo Medição": null,
    "Data da Última Medição/Movimentação": null,
    "Dias sem medição": null,
    "Dias sem movimentação": null,
    "Pendências": null,
    "Órgão Responsável pela pendência": null,
    "Engenheiro Responsável": null,
    "Situação_1": null,
    "Área": null
  },
  {
    "Data Inicial": null,
    "Modalidade do Repasse": null,
    "Proposta/ Demanda": null,
    "Termo de  Formalização": null,
    "Número do Termo": null,
    "Data de Assinatura": null,
    "Ano": null,
    "Vigência": null,
    "Cláusula Suspensiva": null,
    "Esfera": null,
    "Situação": null,
    "Parlamentar": null,
    "Partido Político": null,
    "Código da Emenda": 202181000652,
    "Função": "Máquina",
    "Subfunção": null,
    "Código da Receita": null,
    "Repasse": null,
    "Contrapartida": null,
    "Ministério": null,
    "Programa": null,
    "Objeto": null,
    "Conta Bancária": null,
    "Valor Liberado": null,
    "Data do depósito": null,
    "Modalidade": null,
    "Número/Ano": null,
    "Contrato nº": null,
    "Contratada": null,
    "Vigência do Contrato": null,
    "Assinatura do Contrato": null,
    "Término da Vigência": null,
    "Aditamento de vigência": null,
    "Prazo de Execução": null,
    "Ordem de Início de Serviço": null,
    "Término da Execução": null,
    "Aditamento de Execução": null,
    "Valor do Contrato": null,
    "Ficha Orçamentária RP": null,
    "Nota de Empenho RP": null,
    "RP Vigente": null,
    "Ficha Orçamentária CP": null,
    "Nota de Empenho CP": null,
    "CP Vigente": null,
    "Nota de Empenho Excl": null,
    "Ficha Orçamentária Excl": null,
    "CP Exclusiva/Recurso Próprio": null,
    "Aditamento de Valor": null,
    "CNO": null,
    "% Medição": null,
    "Valor Pago": null,
    "% Pago": null,
    "Saldo de RP": null,
    "Saldo na conta (rendimentos)": null,
    "Prestação de Contas": null,
    "Processo SPD": null,
    "Processo Crédito Adicional": null,
    "Processo Licitatório": null,
    "Processo Medição": null,
    "Data da Última Medição/Movimentação": null,
    "Dias sem medição": null,
    "Dias sem movimentação": null,
    "Pendências": null,
    "Órgão Responsável pela pendência": null,
    "Engenheiro Responsável": null,
    "Situação_1": null,
    "Área": null
  }
];
